/// <mls fileReference="_102040_/l2/molecules/groupviewhierarchy/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:47:05.782Z.

export const group = 'groupViewHierarchy';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupViewHierarchy/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupviewhierarchy--ml-hierarchy-orgchart', layout: { hierarchy: 'orgchart' }, defs: '/_102040_/l2/molecules/groupviewhierarchy/ml-hierarchy-orgchart.defs' },
    { tag: 'groupviewhierarchy--ml-hierarchy-tree', layout: { hierarchy: 'tree' }, defs: '/_102040_/l2/molecules/groupviewhierarchy/ml-hierarchy-tree.defs' },
    { tag: 'groupviewhierarchy--ml-hierarchy-tree-diagram', layout: { hierarchy: 'tree' }, defs: '/_102040_/l2/molecules/groupviewhierarchy/ml-hierarchy-tree-diagram.defs' },
    { tag: 'groupviewhierarchy--ml-view-hierarchy-mindmap', layout: { hierarchy: 'mindmap' }, defs: '/_102040_/l2/molecules/groupviewhierarchy/ml-view-hierarchy-mindmap.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'You need to show reporting structure and leadership layers.', recommended: [] },
    { scenario: 'You are mapping systems or services with multiple branches open.', recommended: ['groupviewhierarchy--ml-hierarchy-tree-diagram'] },
    { scenario: 'You want familiar file or category navigation with expandable items.', recommended: ['groupviewhierarchy--ml-hierarchy-tree'] },
    { scenario: 'You are brainstorming ideas around a central topic.', recommended: [] },
];

export const skill = `# groupViewHierarchy — available molecules (mls-102040)

Group objective: Displays hierarchical data structures with parent-child relationships. Uses recursive Node slot tags with free content that can nest indefinitely. Supports expand/collapse of nodes with children, accordion mode (one per level), and expand-all. Implementations include tree view, org chart, cascader, nested list, and mind map.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| You need to show reporting structure and leadership layers. | — |
| You are mapping systems or services with multiple branches open. | ml-hierarchy-tree-diagram |
| You want familiar file or category navigation with expandable items. | ml-hierarchy-tree |
| You are brainstorming ideas around a central topic. | — |

## Molecules (4)

- **groupviewhierarchy--ml-hierarchy-orgchart** · hierarchy: orgchart — Render an interactive organizational-chart-style hierarchy tree where each node is displayed as a card-like button connected to its children by vertical and horizontal lines. Users can expand or collapse branches, navigate the tree with the keyboard, and select individual nodes.
- **groupviewhierarchy--ml-hierarchy-tree** · hierarchy: tree — Display a hierarchical tree structure that allows users to navigate nested levels by expanding and collapsing nodes, while emitting events for interactions. The tree renders user-provided nested content, supports disabled states, and adapts to single or multiple selection patterns without maintaining selection state internally.
- **groupviewhierarchy--ml-hierarchy-tree-diagram** · hierarchy: tree — Render an interactive hierarchy tree in a horizontal diagram style where each node is shown with a circular state indicator, a toggle button, and its label, connected to children through decorative SVG connectors. The layout flows top-to-bottom with children arranged to the right, providing a clear branching visual metaphor.
- **groupviewhierarchy--ml-view-hierarchy-mindmap** · hierarchy: mindmap — Present a mind-map hierarchy with a configurable central node and radial child layout. Enable users to explore parent-child relationships through expand and collapse interactions, navigate the view via pan and zoom, and interact with nodes while delegating all structural changes to the consumer.
`;
