/// <mls fileReference="_102040_/l2/molecules/groupenterdateinterval/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:45:59.398Z.

export const group = 'groupEnterDateInterval';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupEnterDateInterval/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupenterdateinterval--ml-date-interval-drag', layout: { intervalInput: 'drag' }, defs: '/_102040_/l2/molecules/groupenterdateinterval/ml-date-interval-drag.defs' },
    { tag: 'groupenterdateinterval--ml-date-interval-presets', layout: { intervalInput: 'presets' }, defs: '/_102040_/l2/molecules/groupenterdateinterval/ml-date-interval-presets.defs' },
    { tag: 'groupenterdateinterval--ml-date-range-dual-calendar', layout: { intervalInput: 'dual-calendar' }, defs: '/_102040_/l2/molecules/groupenterdateinterval/ml-date-range-dual-calendar.defs' },
    { tag: 'groupenterdateinterval--ml-month-year-range', layout: { intervalInput: 'dual-calendar' }, defs: '/_102040_/l2/molecules/groupenterdateinterval/ml-month-year-range.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Users should drag across a single calendar for quick selection.', recommended: ['groupenterdateinterval--ml-date-interval-drag'] },
    { scenario: 'Longer ranges need two months visible at once.', recommended: ['groupenterdateinterval--ml-date-range-dual-calendar'] },
    { scenario: 'Reporting requires full months or year spans rather than exact days.', recommended: ['groupenterdateinterval--ml-month-year-range'] },
    { scenario: 'Fast selection from predefined ranges like last 7 or 30 days.', recommended: ['groupenterdateinterval--ml-date-interval-presets'] },
];

export const skill = `# groupEnterDateInterval — available molecules (mls-102040)

Group objective: Allows the user to input a date range with a start date and an end date (no time). Ideal for vacation periods, report filters, campaign durations, contract validity, and hotel or flight booking dates. Implementations include date range picker with dual calendar, inline date range, and range picker with presets.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Users should drag across a single calendar for quick selection. | ml-date-interval-drag |
| Longer ranges need two months visible at once. | ml-date-range-dual-calendar |
| Reporting requires full months or year spans rather than exact days. | ml-month-year-range |
| Fast selection from predefined ranges like last 7 or 30 days. | ml-date-interval-presets |

## Molecules (4)

- **groupenterdateinterval--ml-date-interval-drag** · intervalInput: drag — Allow the user to select a date range by pressing and dragging across an always-visible single-month calendar grid. Pressing down on any selectable day anchors the start date, and releasing the pointer on another day confirms the end date. The component shows a live preview of the range as the user drags and highlights invalid end-date candidates in red. It supports min/max date bounds, configurable minimum and maximum range lengths, optional same-day selection, and disabled, readonly, loading, and error states.
- **groupenterdateinterval--ml-date-interval-presets** · intervalInput: presets — Enable users to select a date range through predefined period shortcuts or custom start and end dates, conforming to the groupEnterDateInterval contract. The component presents the range differently depending on whether the user is editing or viewing the value.
- **groupenterdateinterval--ml-date-range-dual-calendar** · intervalInput: dual-calendar — Allow the user to select a date range through two separate trigger buttons — one for the start date and one for the end date — that open a panel showing two side-by-side monthly calendars. Clicking the start trigger opens the calendars in start-selection mode; clicking the end trigger enters end-selection mode directly when a start date is already set. A hover preview highlights the tentative range as the user moves over day cells. The component enforces min/max date bounds, optional minimum and maximum range lengths, same-day restrictions, and supports disabled, readonly, required, loading, and error states.
- **groupenterdateinterval--ml-month-year-range** · intervalInput: dual-calendar — Enable users to select a date range limited to month and year granularity. The molecule presents two independent year-navigable month grids, highlights the chosen interval, and communicates the selection through the groupEnterDateInterval contract.
`;
