/// <mls fileReference="_102040_/l2/molecules/groupselectmany/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:48.067Z.

export const group = 'groupSelectMany';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupSelectMany/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupselectmany--ml-dual-list-select', layout: { selectMany: 'dual-list' }, defs: '/_102040_/l2/molecules/groupselectmany/ml-dual-list-select.defs' },
    { tag: 'groupselectmany--ml-multi-checkbox-list', layout: { selectMany: 'checkbox-list' }, defs: '/_102040_/l2/molecules/groupselectmany/ml-multi-checkbox-list.defs' },
    { tag: 'groupselectmany--ml-multi-select-dropdown', layout: { selectMany: 'dropdown' }, defs: '/_102040_/l2/molecules/groupselectmany/ml-multi-select-dropdown.defs' },
    { tag: 'groupselectmany--ml-popover-multi-select', layout: { selectMany: 'popover' }, defs: '/_102040_/l2/molecules/groupselectmany/ml-popover-multi-select.defs' },
    { tag: 'groupselectmany--ml-table-multi-select', defs: null /* ⚠ no .defs.ts — outside the contract */ },
    { tag: 'groupselectmany--ml-tree-multi-select', layout: { selectMany: 'tree' }, defs: '/_102040_/l2/molecules/groupselectmany/ml-tree-multi-select.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Users need to move items between two distinct lists with clear selection counts.', recommended: ['groupselectmany--ml-dual-list-select'] },
    { scenario: 'All options should stay visible without opening a panel.', recommended: ['groupselectmany--ml-multi-checkbox-list', 'groupselectmany--ml-table-multi-select'] },
    { scenario: 'Screen space is limited and the list can be searched or filtered.', recommended: ['groupselectmany--ml-multi-select-dropdown', 'groupselectmany--ml-popover-multi-select'] },
    { scenario: 'Selections come from nested categories or organizational hierarchies.', recommended: ['groupselectmany--ml-tree-multi-select'] },
    { scenario: 'You need a compact, chip-based picker with a customizable trigger.', recommended: ['groupselectmany--ml-popover-multi-select'] },
    { scenario: 'Each option has multiple comparable attributes and the user picks several rows.', recommended: ['groupselectmany--ml-table-multi-select'] },
];

export const skill = `# groupSelectMany — available molecules (mls-102040)

Group objective: Allows the user to select one or more options from a list. Value is a comma-separated string of selected item values. Supports searchable filtering, min/max selection limits, grouped items, and disabled options. Implementations include checkbox group, chips/tags, multi-select dropdown, dual list (transfer list), card grid with selection, toggle group, and table (checkbox rows with column headers for comparing attributes).

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Users need to move items between two distinct lists with clear selection counts. | ml-dual-list-select |
| All options should stay visible without opening a panel. | ml-multi-checkbox-list, ml-table-multi-select |
| Screen space is limited and the list can be searched or filtered. | ml-multi-select-dropdown, ml-popover-multi-select |
| Selections come from nested categories or organizational hierarchies. | ml-tree-multi-select |
| You need a compact, chip-based picker with a customizable trigger. | ml-popover-multi-select |
| Each option has multiple comparable attributes and the user picks several rows. | ml-table-multi-select |

## Molecules (6)

- **groupselectmany--ml-dual-list-select** · selectMany: dual-list — Allow the user to select multiple items from a side-by-side two-panel layout. The left panel shows available (unselected) items and the right panel shows selected items. Users transfer items between panels using per-item Add/Remove buttons or bulk "Add all" / "Remove all" actions. The component supports optional search filtering, grouping, min/max selection limits, and a read-only view mode.
- **groupselectmany--ml-multi-checkbox-list** · selectMany: checkbox-list — Allow the user to select multiple options from a vertical list of checkbox-style buttons. Each item shows a visible check indicator when selected. The component supports optional search filtering, grouping, min/max selection limits, a required flag, and a read-only view mode that renders selected items inline.
- **groupselectmany--ml-multi-select-dropdown** · selectMany: dropdown — Provide a multi-select field that allows users to choose one or more options from a dropdown list. The field supports grouped options, search filtering, selection limits, and validation states, adapting its behavior between editing and viewing modes.
- **groupselectmany--ml-popover-multi-select** · selectMany: popover — Act as a compact multi-selection control that opens a floating panel when activated. It allows choosing multiple options without keeping the selection interface permanently visible, making it suitable for filter bars and space-constrained interfaces.
- **groupselectmany--ml-table-multi-select** — ⚠ outside the contract: no .defs.ts (objective unavailable; read the molecule file before using it).
- **groupselectmany--ml-tree-multi-select** · selectMany: tree — Provide a hierarchical tree interface that allows users to select multiple nodes. Parent nodes can be expanded or collapsed. Selecting a parent selects all its descendants. The component supports searching to filter nodes and emits the selected node identifiers following the groupSelectMany contract.
`;
