/// <mls fileReference="_102040_/l2/molecules/groupnotifyuser/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:32.398Z.

export const group = 'groupNotifyUser';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupNotifyUser/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupnotifyuser--ml-alert-modal', layout: { feedback: 'modal' }, defs: '/_102040_/l2/molecules/groupnotifyuser/ml-alert-modal.defs' },
    { tag: 'groupnotifyuser--ml-contextual-feedback', layout: { feedback: 'inline' }, defs: '/_102040_/l2/molecules/groupnotifyuser/ml-contextual-feedback.defs' },
    { tag: 'groupnotifyuser--ml-notify-banner', layout: { feedback: 'banner' }, defs: '/_102040_/l2/molecules/groupnotifyuser/ml-notify-banner.defs' },
    { tag: 'groupnotifyuser--ml-toast-notification', layout: { feedback: 'toast' }, defs: '/_102040_/l2/molecules/groupnotifyuser/ml-toast-notification.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Persistent update at the top of the page with a clear action.', recommended: ['groupnotifyuser--ml-notify-banner'] },
    { scenario: 'Quick success confirmation that should disappear automatically.', recommended: ['groupnotifyuser--ml-toast-notification'] },
    { scenario: 'Critical failure that must be acknowledged before continuing.', recommended: ['groupnotifyuser--ml-alert-modal'] },
    { scenario: 'Inline guidance tied to a specific form field or action.', recommended: ['groupnotifyuser--ml-contextual-feedback'] },
];

export const skill = `# groupNotifyUser — available molecules (mls-102040)

Group objective: Informs the user about events, status changes, or action results. Controlled via visible property. Supports notification types (info, success, warning, error), auto-dismiss with configurable duration, position hints, dismissible toggle, and optional action slot. Implementations include toast, snackbar, banner, alert, and inline alert.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Persistent update at the top of the page with a clear action. | ml-notify-banner |
| Quick success confirmation that should disappear automatically. | ml-toast-notification |
| Critical failure that must be acknowledged before continuing. | ml-alert-modal |
| Inline guidance tied to a specific form field or action. | ml-contextual-feedback |

## Molecules (4)

- **groupnotifyuser--ml-alert-modal** · feedback: modal — Present a blocking modal alert for critical or destructive actions that demands user attention and an explicit choice before proceeding. Communicate severity through visual cues and provide clear options to confirm or cancel the action.
- **groupnotifyuser--ml-contextual-feedback** · feedback: inline — Provide contextual feedback messages inside forms, positioned near related fields or sections. Communicates success, error, warning, or info states through text, optional icon, and optional action. Supports dismissible and persistent modes, automatic dismissal timing, and accessibility announcements.
- **groupnotifyuser--ml-notify-banner** · feedback: banner — Display a contextual inline or floating notification banner that communicates a status message to the user. The banner supports four semantic types (info, success, warning, error), an optional title, an optional action link, an optional custom icon, a dismiss button, automatic timed dismissal, and configurable screen positioning.
- **groupnotifyuser--ml-toast-notification** · feedback: toast — Provide ephemeral floating notifications that appear in a screen corner, slide in and out smoothly, indicate different severity levels through color and icon, dismiss automatically after a set time or manually via a close control, optionally offer a secondary action, and stack vertically when multiple instances are active.
`;
