/// <mls fileReference="_102040_/l2/molecules/groupenterdatetimeinterval/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:04.444Z.

export const group = 'groupEnterDateTimeInterval';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupEnterDateTimeInterval/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupenterdatetimeinterval--ml-datetime-interval-timeline', layout: { intervalInput: 'timeline' }, defs: '/_102040_/l2/molecules/groupenterdatetimeinterval/ml-datetime-interval-timeline.defs' },
    { tag: 'groupenterdatetimeinterval--ml-enter-datetime-interval', layout: { intervalInput: 'fields' }, defs: '/_102040_/l2/molecules/groupenterdatetimeinterval/ml-enter-datetime-interval.defs' },
    { tag: 'groupenterdatetimeinterval--ml-event-duration-interval', layout: { intervalInput: 'duration' }, defs: '/_102040_/l2/molecules/groupenterdatetimeinterval/ml-event-duration-interval.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Need a visual timeline to drag across a maintenance window or availability block.', recommended: ['groupenterdatetimeinterval--ml-datetime-interval-timeline'] },
    { scenario: 'Simple form-driven meeting scheduling with start/end fields and validation.', recommended: ['groupenterdatetimeinterval--ml-enter-datetime-interval'] },
    { scenario: 'Bookings with strict min/max duration rules and event context.', recommended: ['groupenterdatetimeinterval--ml-event-duration-interval'] },
    { scenario: 'Users need a clear range input but no duration constraints.', recommended: ['groupenterdatetimeinterval--ml-enter-datetime-interval'] },
];

export const skill = `# groupEnterDateTimeInterval — available molecules (mls-102040)

Group objective: Allows the user to input a date+time range with a start datetime and an end datetime. Ideal for meeting scheduling, room reservations, maintenance windows, task time tracking, and any booking that requires exact start and end timestamps. Implementations include datetime range picker, event scheduler, and booking widget.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Need a visual timeline to drag across a maintenance window or availability block. | ml-datetime-interval-timeline |
| Simple form-driven meeting scheduling with start/end fields and validation. | ml-enter-datetime-interval |
| Bookings with strict min/max duration rules and event context. | ml-event-duration-interval |
| Users need a clear range input but no duration constraints. | ml-enter-datetime-interval |

## Molecules (3)

- **groupenterdatetimeinterval--ml-datetime-interval-timeline** · intervalInput: timeline — Allow the user to view and edit a datetime interval through a visual timeline track that renders two draggable markers representing the start and end datetimes, together with two datetime-local inputs arranged in a two-column grid. In view mode the component collapses to a single formatted range string. When editing, the timeline visually fills the segment between the two selected instants.
- **groupenterdatetimeinterval--ml-enter-datetime-interval** · intervalInput: fields — Allow the user to select a datetime interval by clicking separate start and end trigger buttons that each expand an inline picker panel. The component shows a live formatted preview of the selected range above the trigger buttons and supports individual confirmation and clearing of each field. In view mode the range is displayed as plain text without any interactive controls.
- **groupenterdatetimeinterval--ml-event-duration-interval** · intervalInput: duration — Enable users to define an event time interval by providing a start and end date and time. The molecule automatically calculates the duration between the two points and presents it to the user. It supports defining the interval by directly setting the end, or by providing a duration in minutes or hours that the molecule converts into an end time. The molecule handles validation, boundary restrictions, and distinct presentation modes for editing and viewing.
`;
