/// <mls fileReference="_102040_/l2/molecules/groupenternumberinterval/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:12.154Z.

export const group = 'groupEnterNumberInterval';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupEnterNumberInterval/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupenternumberinterval--ml-number-interval-inputs', defs: '/_102040_/l2/molecules/groupenternumberinterval/ml-number-interval-inputs.defs' },
    { tag: 'groupenternumberinterval--ml-number-range-slider', defs: '/_102040_/l2/molecules/groupenternumberinterval/ml-number-range-slider.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Visual continuous selection (price filters, dashboards)', recommended: ['groupenternumberinterval--ml-number-range-slider'] },
    { scenario: 'Precise numeric entry with keyboard (forms, admin panels)', recommended: ['groupenternumberinterval--ml-number-interval-inputs'] },
    { scenario: 'Touch-friendly mobile range picking', recommended: ['groupenternumberinterval--ml-number-range-slider'] },
    { scenario: 'Large value domains needing exact from/to figures', recommended: ['groupenternumberinterval--ml-number-interval-inputs'] },
    { scenario: 'Bounded interval with min/max gap constraints', recommended: ['groupenternumberinterval--ml-number-range-slider', 'groupenternumberinterval--ml-number-interval-inputs'] },
    { scenario: 'Decimal measurements (weight, length, ratings)', recommended: ['groupenternumberinterval--ml-number-range-slider', 'groupenternumberinterval--ml-number-interval-inputs'] },
    { scenario: 'Compact UI where a slider saves vertical space', recommended: ['groupenternumberinterval--ml-number-range-slider'] },
    { scenario: 'Accessibility-first keyboard data entry', recommended: ['groupenternumberinterval--ml-number-interval-inputs'] },
];

export const skill = `# groupEnterNumberInterval — available molecules (mls-102040)

Group objective: Allows the user to input a numeric range with a lower and an upper value. Ideal for price bands, age brackets, value filters, weight or measurement ranges, and any bounded numeric interval. Supports min/max bounds, step, decimals, locale formatting, and minimum/maximum gap between values. Implementations include dual-handle range slider, from/to number inputs, and histogram range.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Visual continuous selection (price filters, dashboards) | ml-number-range-slider |
| Precise numeric entry with keyboard (forms, admin panels) | ml-number-interval-inputs |
| Touch-friendly mobile range picking | ml-number-range-slider |
| Large value domains needing exact from/to figures | ml-number-interval-inputs |
| Bounded interval with min/max gap constraints | ml-number-range-slider, ml-number-interval-inputs |
| Decimal measurements (weight, length, ratings) | ml-number-range-slider, ml-number-interval-inputs |
| Compact UI where a slider saves vertical space | ml-number-range-slider |
| Accessibility-first keyboard data entry | ml-number-interval-inputs |

## Molecules (2)

- **groupenternumberinterval--ml-number-interval-inputs** — A molecule that captures a numeric interval composed of a lower bound and an upper bound, presented as two side-by-side numeric inputs. It is designed to be used wherever a min/max range must be entered, such as a minimum and maximum price, quantity range, or any other bounded numeric pair, and it operates under the groupEnterNumberInterval contract.
- **groupenternumberinterval--ml-number-range-slider** — Provide a dual-handle range slider molecule that allows the user to select a numeric interval (a minimum and a maximum value) on a single bounded track, primarily intended for use cases such as price-range filtering.
`;
