/// <mls fileReference="_102040_/l2/molecules/groupenterboolean/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:45:45.988Z.

export const group = 'groupEnterBoolean';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupEnterBoolean/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupenterboolean--ml-boolean-segmented', layout: { boolean: 'segmented', labelPlacement: 'top' }, defs: '/_102040_/l2/molecules/groupenterboolean/ml-boolean-segmented.defs' },
    { tag: 'groupenterboolean--ml-checkbox-preference', layout: { boolean: 'checkbox', labelPlacement: 'inline' }, defs: '/_102040_/l2/molecules/groupenterboolean/ml-checkbox-preference.defs' },
    { tag: 'groupenterboolean--ml-toggle-icon', layout: { boolean: 'icon', labelPlacement: 'top' }, defs: '/_102040_/l2/molecules/groupenterboolean/ml-toggle-icon.defs' },
    { tag: 'groupenterboolean--ml-toggle-switch', layout: { boolean: 'toggle', labelPlacement: 'top' }, defs: '/_102040_/l2/molecules/groupenterboolean/ml-toggle-switch.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Need an explicit yes/no choice that reads like a segmented control in forms.', recommended: ['groupenterboolean--ml-boolean-segmented'] },
    { scenario: 'Require a legal agreement or acknowledgement before submission.', recommended: ['groupenterboolean--ml-checkbox-preference'] },
    { scenario: 'Prefer a compact icon-based toggle for dense preference lists.', recommended: ['groupenterboolean--ml-toggle-icon'] },
    { scenario: 'Need a familiar settings switch for longer configuration screens.', recommended: ['groupenterboolean--ml-toggle-switch'] },
];

export const skill = `# groupEnterBoolean — available molecules (mls-102040)

Group objective: Allows the user to input a true/false decision. Value is boolean — starts as false until the user changes it. Supports Label and Helper slot tags. Implementations are toggle/switch and checkbox, fully interchangeable by swapping the component tag.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Need an explicit yes/no choice that reads like a segmented control in forms. | ml-boolean-segmented |
| Require a legal agreement or acknowledgement before submission. | ml-checkbox-preference |
| Prefer a compact icon-based toggle for dense preference lists. | ml-toggle-icon |
| Need a familiar settings switch for longer configuration screens. | ml-toggle-switch |

## Molecules (4)

- **groupenterboolean--ml-boolean-segmented** · boolean: segmented, labelPlacement: top — Enable the user to choose between two mutually exclusive boolean states through a pair of side-by-side options. The molecule must clearly identify the current selection, inform the system of changes, and adapt its interactivity and presentation according to editing, viewing, disabled, and error conditions.
- **groupenterboolean--ml-checkbox-preference** · boolean: checkbox, labelPlacement: inline — Provide a boolean preference control that allows users to mark or unmark an option. It must support an interactive editing mode for changing the value and a read-only view mode for displaying the current state, while clearly communicating validation issues.
- **groupenterboolean--ml-toggle-icon** · boolean: icon, labelPlacement: top — A boolean input component that behaves as a toggle switch with distinct icons for on and off states. It supports editing and viewing modes, optional labeling, helper text, error display, and disabled state, emitting events on user-driven state changes.
- **groupenterboolean--ml-toggle-switch** · boolean: toggle, labelPlacement: top — A boolean input molecule that enables users to switch between two mutually exclusive states. It provides an interactive toggle during editing mode and displays the current selection as static text during read-only mode. It reports value changes, focus, and blur to the surrounding system, and presents labels, contextual guidance, and validation errors according to its current state.
`;
