/// <mls fileReference="_102040_/l2/molecules/groupshowprogress/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:53.152Z.

export const group = 'groupShowProgress';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupShowProgress/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupshowprogress--ml-circular-progress', layout: { progress: 'circular' }, defs: '/_102040_/l2/molecules/groupshowprogress/ml-circular-progress.defs' },
    { tag: 'groupshowprogress--ml-indeterminate-spinner', layout: { progress: 'spinner' }, defs: '/_102040_/l2/molecules/groupshowprogress/ml-indeterminate-spinner.defs' },
    { tag: 'groupshowprogress--ml-linear-progress', layout: { progress: 'linear' }, defs: '/_102040_/l2/molecules/groupshowprogress/ml-linear-progress.defs' },
    { tag: 'groupshowprogress--ml-segmented-progress', layout: { progress: 'segmented' }, defs: '/_102040_/l2/molecules/groupshowprogress/ml-segmented-progress.defs' },
    { tag: 'groupshowprogress--ml-upload-progress-indicator', layout: { progress: 'linear' }, defs: '/_102040_/l2/molecules/groupshowprogress/ml-upload-progress-indicator.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Need a compact percentage indicator for a determinate task.', recommended: ['groupshowprogress--ml-circular-progress'] },
    { scenario: 'Duration is unknown and the UI should stay lightweight.', recommended: ['groupshowprogress--ml-indeterminate-spinner'] },
    { scenario: 'Show a full-width progress bar in a form or modal.', recommended: ['groupshowprogress--ml-linear-progress'] },
    { scenario: 'Represent a multi-step workflow with segment milestones.', recommended: ['groupshowprogress--ml-segmented-progress'] },
    { scenario: 'Highlight file transfer completion with a percent readout.', recommended: ['groupshowprogress--ml-upload-progress-indicator'] },
];

export const skill = `# groupShowProgress — available molecules (mls-102040)

Group objective: Indicates the progress of an operation or process. Visual primitive designed for composition inside other components. Supports determinate mode (0-100%) and indeterminate mode (unknown duration). Implementations include progress bar, progress ring/circle, spinner, and percentage indicator.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Need a compact percentage indicator for a determinate task. | ml-circular-progress |
| Duration is unknown and the UI should stay lightweight. | ml-indeterminate-spinner |
| Show a full-width progress bar in a form or modal. | ml-linear-progress |
| Represent a multi-step workflow with segment milestones. | ml-segmented-progress |
| Highlight file transfer completion with a percent readout. | ml-upload-progress-indicator |

## Molecules (5)

- **groupshowprogress--ml-circular-progress** · progress: circular — Provide a circular progress indicator that displays completion percentage or ongoing activity status. It communicates progress through a circular ring that fills proportionally to a numeric value or signals indeterminate activity when no value is available.
- **groupshowprogress--ml-indeterminate-spinner** · progress: spinner — Provide a purely visual loading indicator for ongoing processes that lack a measurable completion percentage. It communicates activity through continuous motion and optional accompanying text, functioning either inline or as a container overlay.
- **groupshowprogress--ml-linear-progress** · progress: linear — A linear progress indicator for the groupShowProgress group that visually communicates completion status or ongoing activity. It supports determinate mode to show exact percentage completion and indeterminate mode to indicate that an operation is in progress without a known duration. The component is purely visual and does not emit events.
- **groupshowprogress--ml-segmented-progress** · progress: segmented — Provide visual feedback of progress to the user. It indicates how much of an operation or process has been completed, or that activity is occurring when no specific completion percentage is known.
- **groupshowprogress--ml-upload-progress-indicator** · progress: linear — Provide a visual indicator that communicates the progress of an upload operation. The component reflects whether the progress is known, unknown, or finished, and optionally presents the percentage completed.
`;
