/// <mls fileReference="_102040_/l2/molecules/grouptriggeraction/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:55.539Z.

export const group = 'groupTriggerAction';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupTriggerAction/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'grouptriggeraction--ml-button-group', layout: { actionStyle: 'standard' }, defs: '/_102040_/l2/molecules/grouptriggeraction/ml-button-group.defs' },
    { tag: 'grouptriggeraction--ml-button-standard', layout: { actionStyle: 'standard' }, defs: '/_102040_/l2/molecules/grouptriggeraction/ml-button-standard.defs' },
    { tag: 'grouptriggeraction--ml-icon-button', layout: { actionStyle: 'icon' }, defs: '/_102040_/l2/molecules/grouptriggeraction/ml-icon-button.defs' },
    { tag: 'grouptriggeraction--ml-kebab-action-trigger', layout: { actionStyle: 'kebab' }, defs: '/_102040_/l2/molecules/grouptriggeraction/ml-kebab-action-trigger.defs' },
    { tag: 'grouptriggeraction--ml-pagination-control', layout: { actionStyle: 'standard' }, defs: '/_102040_/l2/molecules/grouptriggeraction/ml-pagination-control.defs' },
    { tag: 'grouptriggeraction--ml-split-button', layout: { actionStyle: 'split' }, defs: '/_102040_/l2/molecules/grouptriggeraction/ml-split-button.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Ação primária única com rótulo visível (Salvar, Enviar, Confirmar)', recommended: ['grouptriggeraction--ml-button-standard'] },
    { scenario: 'Ação compacta só com ícone (toolbar, cards densos)', recommended: ['grouptriggeraction--ml-icon-button'] },
    { scenario: 'Várias ações relacionadas exibidas juntas (alinhamento, filtros)', recommended: ['grouptriggeraction--ml-button-group'] },
    { scenario: 'Ação principal + alternativas no mesmo controle (Publicar / Agendar)', recommended: ['grouptriggeraction--ml-split-button'] },
    { scenario: 'Menu de overflow para ações secundárias ou contextuais (⋮)', recommended: ['grouptriggeraction--ml-kebab-action-trigger'] },
    { scenario: 'Navegar entre páginas de um conjunto de dados (listas, tabelas)', recommended: ['grouptriggeraction--ml-pagination-control'] },
    { scenario: 'Disparar comando imediato com feedback de loading/disabled', recommended: ['grouptriggeraction--ml-button-standard', 'grouptriggeraction--ml-icon-button', 'grouptriggeraction--ml-button-group', 'grouptriggeraction--ml-split-button', 'grouptriggeraction--ml-kebab-action-trigger'] },
    { scenario: 'Trocar de página emitindo evento com a página selecionada', recommended: ['grouptriggeraction--ml-pagination-control'] },
];

export const skill = `# groupTriggerAction — available molecules (mls-102040)

Group objective: Allows the user to execute an action or command. Supports Label and Icon slot tags with flexible composition (text only, icon only, or both). Configurable variant (primary, secondary, danger, ghost, link), size, loading state, and icon position. Implementations include button, icon button, FAB, split button, and button group.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Ação primária única com rótulo visível (Salvar, Enviar, Confirmar) | ml-button-standard |
| Ação compacta só com ícone (toolbar, cards densos) | ml-icon-button |
| Várias ações relacionadas exibidas juntas (alinhamento, filtros) | ml-button-group |
| Ação principal + alternativas no mesmo controle (Publicar / Agendar) | ml-split-button |
| Menu de overflow para ações secundárias ou contextuais (⋮) | ml-kebab-action-trigger |
| Navegar entre páginas de um conjunto de dados (listas, tabelas) | ml-pagination-control |
| Disparar comando imediato com feedback de loading/disabled | ml-button-standard, ml-icon-button, ml-button-group, ml-split-button, ml-kebab-action-trigger |
| Trocar de página emitindo evento com a página selecionada | ml-pagination-control |

## Molecules (6)

- **grouptriggeraction--ml-button-group** · actionStyle: standard — A group of related buttons that act as a single control unit, allowing users to choose between related actions or options. The buttons appear visually connected without gaps, supporting different layouts, sizes, and visual styles.
- **grouptriggeraction--ml-button-standard** · actionStyle: standard — A standard button molecule for the groupTriggerAction group that triggers actions when activated. It supports text labels, icons, multiple sizes, visual styles, loading states with a spinner indicator, and disabled states. Designed for corporate interfaces such as ERP, CRM, HR, Financial, and Logistics systems.
- **grouptriggeraction--ml-icon-button** · actionStyle: icon — Botão compacto contendo apenas ícone para execução de ações rápidas em barras de ferramentas, tabelas e listas. Deve permitir que o usuário execute uma ação imediata ao interagir com o ícone, apresentando-se em diferentes tamanhos e respeitando estados de interação definidos pelo grupo groupTriggerAction.
- **grouptriggeraction--ml-kebab-action-trigger** · actionStyle: kebab — A compact contextual trigger presented as a kebab or ellipsis button. When activated by the user, it signals the system to open an external contextual menu. Designed for dense interfaces such as data tables, where each row requires access to secondary actions without cluttering the primary view.
- **grouptriggeraction--ml-pagination-control** · actionStyle: standard — Um controle de paginação que exibe números de páginas clicáveis e botões de navegação (primeira, anterior, próxima, última), permitindo ao usuário navegar entre páginas de um conjunto de dados. Segue o contrato do grupo groupTriggerAction, despachando um evento action com o número da página alvo no detalhe.
- **grouptriggeraction--ml-split-button** · actionStyle: split — Provide a split button that presents a primary action together with a dropdown of secondary actions, allowing users to execute the main action or select an alternative from the related options within the groupTriggerAction group.
`;
