/// <mls fileReference="_102040_/l2/molecules/groupscancode/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:40.266Z.

export const group = 'groupScanCode';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupScanCode/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupscancode--ml-scan-code', defs: '/_102040_/l2/molecules/groupscancode/ml-scan-code.defs' },
    { tag: 'groupscancode--ml-scan-code-1d', defs: '/_102040_/l2/molecules/groupscancode/ml-scan-code-1d.defs' },
    { tag: 'groupscancode--ml-scan-document', defs: '/_102040_/l2/molecules/groupscancode/ml-scan-document.defs' },
    { tag: 'groupscancode--ml-scan-ocr', defs: '/_102040_/l2/molecules/groupscancode/ml-scan-ocr.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Scan linear barcodes on retail labels or tickets.', recommended: ['groupscancode--ml-scan-code-1d'] },
    { scenario: 'Capture QR codes for payments, check-ins, or deep links.', recommended: ['groupscancode--ml-scan-code'] },
    { scenario: 'Extract text blocks from receipts or invoices with OCR.', recommended: ['groupscancode--ml-scan-ocr'] },
    { scenario: 'Capture full-page documents or IDs with edge detection.', recommended: ['groupscancode--ml-scan-document'] },
];

export const skill = `# groupScanCode — available molecules (mls-102040)

Group objective: Captures information via camera (QR code, barcode, document). Component captures image frames and emits them; the page is responsible for decoding via BFF. Supports rear/front camera, auto-capture with configurable interval, and custom result display. Implementations include QR code scanner, barcode reader, document scanner (OCR), and camera viewfinder.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Scan linear barcodes on retail labels or tickets. | ml-scan-code-1d |
| Capture QR codes for payments, check-ins, or deep links. | ml-scan-code |
| Extract text blocks from receipts or invoices with OCR. | ml-scan-ocr |
| Capture full-page documents or IDs with edge detection. | ml-scan-document |

## Molecules (4)

- **groupscancode--ml-scan-code** — Allow the user to capture a video frame from the device camera for code scanning purposes. The component manages the camera lifecycle (open, capture, close), supports front and rear camera selection, optional automatic periodic frame capture, and transitions between trigger, viewfinder, and result states based on whether a scan value has been obtained.
- **groupscancode--ml-scan-code-1d** — A scanner specialized for reading linear 1D barcodes, including EAN-13, EAN-8, UPC-A, Code 128, and Code 39. It operates within the groupScanCode group, periodically emitting captured frames for external decoding while also attempting local decoding when available. Upon successful detection, it emits the barcode format and value. It supports camera selection, adjustable capture frequency, and manages distinct visual states for idle, open, capturing, loading, result, error, and disabled conditions.
- **groupscancode--ml-scan-document** — A scanner molecule that uses the device camera to detect document boundaries, allows manual refinement of detection corners, and produces a rectified cropped image of the document. It follows the groupScanCode contract for scanning workflows.
- **groupscancode--ml-scan-ocr** — Enable users to capture printed text using the device camera and optical character recognition, providing a live preview with a defined capture area, and presenting recognized text for review or correction before confirmation.
`;
