/// <mls fileReference="_102040_/l2/molecules/skill.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:47:13.451Z.

export const project = '102040';

// This project has no local theme.
export const theme = null;

export const groups = [
    { name: 'groupEnterBoolean', molecules: 4, indexDefs: '/_102040_/l2/molecules/groupenterboolean/index.defs' },
    { name: 'groupEnterDate', molecules: 4, indexDefs: '/_102040_/l2/molecules/groupenterdate/index.defs' },
    { name: 'groupEnterDateInterval', molecules: 4, indexDefs: '/_102040_/l2/molecules/groupenterdateinterval/index.defs' },
    { name: 'groupEnterDatetime', molecules: 2, indexDefs: '/_102040_/l2/molecules/groupenterdatetime/index.defs' },
    { name: 'groupEnterDateTimeInterval', molecules: 3, indexDefs: '/_102040_/l2/molecules/groupenterdatetimeinterval/index.defs' },
    { name: 'groupEnterMoney', molecules: 2, indexDefs: '/_102040_/l2/molecules/groupentermoney/index.defs' },
    { name: 'groupEnterNumber', molecules: 3, indexDefs: '/_102040_/l2/molecules/groupenternumber/index.defs' },
    { name: 'groupEnterNumberInterval', molecules: 2, indexDefs: '/_102040_/l2/molecules/groupenternumberinterval/index.defs' },
    { name: 'groupEnterText', molecules: 8, indexDefs: '/_102040_/l2/molecules/groupentertext/index.defs' },
    { name: 'groupEnterTime', molecules: 3, indexDefs: '/_102040_/l2/molecules/groupentertime/index.defs' },
    { name: 'groupEnterTimeInterval', molecules: 6, indexDefs: '/_102040_/l2/molecules/groupentertimeinterval/index.defs' },
    { name: 'groupExpandContent', molecules: 5, indexDefs: '/_102040_/l2/molecules/groupexpandcontent/index.defs' },
    { name: 'groupLocatePosition', molecules: 4, indexDefs: '/_102040_/l2/molecules/grouplocateposition/index.defs' },
    { name: 'groupNavigateSection', molecules: 5, indexDefs: '/_102040_/l2/molecules/groupnavigatesection/index.defs' },
    { name: 'groupNavigateSteps', molecules: 4, indexDefs: '/_102040_/l2/molecules/groupnavigatesteps/index.defs' },
    { name: 'groupNotifyUser', molecules: 4, indexDefs: '/_102040_/l2/molecules/groupnotifyuser/index.defs' },
    { name: 'groupPlayMedia', molecules: 4, indexDefs: '/_102040_/l2/molecules/groupplaymedia/index.defs' },
    { name: 'groupRateItem', molecules: 8, indexDefs: '/_102040_/l2/molecules/grouprateitem/index.defs' },
    { name: 'groupScanCode', molecules: 4, indexDefs: '/_102040_/l2/molecules/groupscancode/index.defs' },
    { name: 'groupSearchContent', molecules: 4, indexDefs: '/_102040_/l2/molecules/groupsearchcontent/index.defs' },
    { name: 'groupSelectFileForUpload', molecules: 5, indexDefs: '/_102040_/l2/molecules/groupselectfileforupload/index.defs' },
    { name: 'groupSelectMany', molecules: 6, indexDefs: '/_102040_/l2/molecules/groupselectmany/index.defs' },
    { name: 'groupSelectOne', molecules: 12, indexDefs: '/_102040_/l2/molecules/groupselectone/index.defs' },
    { name: 'groupShowProgress', molecules: 5, indexDefs: '/_102040_/l2/molecules/groupshowprogress/index.defs' },
    { name: 'groupTriggerAction', molecules: 6, indexDefs: '/_102040_/l2/molecules/grouptriggeraction/index.defs' },
    { name: 'groupViewCard', molecules: 4, indexDefs: '/_102040_/l2/molecules/groupviewcard/index.defs' },
    { name: 'groupViewChart', molecules: 6, indexDefs: '/_102040_/l2/molecules/groupviewchart/index.defs' },
    { name: 'groupViewData', molecules: 5, indexDefs: '/_102040_/l2/molecules/groupviewdata/index.defs' },
    { name: 'groupViewHierarchy', molecules: 4, indexDefs: '/_102040_/l2/molecules/groupviewhierarchy/index.defs' },
    { name: 'groupViewMetric', molecules: 5, indexDefs: '/_102040_/l2/molecules/groupviewmetric/index.defs' },
    { name: 'groupViewTable', molecules: 13, indexDefs: '/_102040_/l2/molecules/groupviewtable/index.defs' },
];

export const skill = `# Molecules — catalog of project mls-102040 (31 groups)

## How to consume it (one level at a time, so the prompt stays small)

1. Read THIS file and choose the GROUPS the page needs. Each group lists its molecules below for exactly that: if a molecule name matches what the region needs, its group is the way in.
2. For each chosen group, read the group catalog (index.defs) and choose the MOLECULE by its full description.
3. Before writing markup, read the group usage contract (the group index.defs points at it).

If the page needs something NO group below covers, answer that there is no molecule available for that region — NEVER invent a tag.

## Available groups

### groupEnterBoolean (4 molecules)
Allows the user to input a true/false decision. Value is boolean — starts as false until the user changes it. Supports Label and Helper slot tags. Implementations are toggle/switch and checkbox, fully interchangeable by swapping the component tag.
Molecules: ml-boolean-segmented, ml-checkbox-preference, ml-toggle-icon, ml-toggle-switch

### groupEnterDate (4 molecules)
Allows the user to input a date only (no time). Ideal for birth dates, due dates, contract effective dates, expiration dates, and any scenario where the time of day is irrelevant. Implementations include date picker, masked date input, inline calendar, and month/year picker.
Molecules: ml-compact-calendar, ml-date-picker, ml-date-shortcut-picker, ml-inline-calendar

### groupEnterDateInterval (4 molecules)
Allows the user to input a date range with a start date and an end date (no time). Ideal for vacation periods, report filters, campaign durations, contract validity, and hotel or flight booking dates. Implementations include date range picker with dual calendar, inline date range, and range picker with presets.
Molecules: ml-date-interval-drag, ml-date-interval-presets, ml-date-range-dual-calendar, ml-month-year-range

### groupEnterDatetime (2 molecules)
Allows the user to input date and/or time values. Ideal for scheduling, deadlines, date ranges, and appointments. Implementations include date picker, time picker, datetime picker, date range picker, inline calendar, month picker, and year picker.
Molecules: ml-datetime-picker, ml-enter-datetime-masked-input

### groupEnterDateTimeInterval (3 molecules)
Allows the user to input a date+time range with a start datetime and an end datetime. Ideal for meeting scheduling, room reservations, maintenance windows, task time tracking, and any booking that requires exact start and end timestamps. Implementations include datetime range picker, event scheduler, and booking widget.
Molecules: ml-datetime-interval-timeline, ml-enter-datetime-interval, ml-event-duration-interval

### groupEnterMoney (2 molecules)
Allows the user to input monetary values with locale-aware formatting. Ideal for prices, payments, budgets, and financial transactions. Handles currency symbols, thousand separators, and decimal precision. Implementations include currency input, price field, money input, and currency converter.
Molecules: ml-currency-input, ml-enter-money-br

### groupEnterNumber (3 molecules)
Allows the user to input numeric values. Ideal for quantities, measurements, percentages, ages, weights, and numeric configurations. Implementations include number input, stepper, slider, percentage input, and quantity selector.
Molecules: ml-floating-number-input, ml-number-input, ml-number-stepper

### groupEnterNumberInterval (2 molecules)
Allows the user to input a numeric range with a lower and an upper value. Ideal for price bands, age brackets, value filters, weight or measurement ranges, and any bounded numeric interval. Supports min/max bounds, step, decimals, locale formatting, and minimum/maximum gap between values. Implementations include dual-handle range slider, from/to number inputs, and histogram range.
Molecules: ml-number-interval-inputs, ml-number-range-slider

### groupEnterText (8 molecules)
Allows the user to input free-form text. Ideal for names, descriptions, comments, emails, passwords, and any textual data. Implementations include input, textarea, password input, masked input, input OTP, search input, and tag input.
Molecules: ml-address-field, ml-cpf-input, ml-enter-text, ml-floating-text-input, ml-multiline-text, ml-password-strength-input, ml-phone-input, ml-tag-input

### groupEnterTime (3 molecules)
Allows the user to input a time only (no date). Ideal for business hours, recurring daily schedules, alarm times, opening and closing times, and shift configurations. Implementations include time picker with scrollable columns, masked time input, time spinner, and clock face.
Molecules: ml-clock-time-picker, ml-enter-time-duration, ml-time-scroll-picker

### groupEnterTimeInterval (6 molecules)
Allows the user to input a time range with a start time and an end time (no date). Ideal for work shifts, business hours configuration, recurring availability windows, class schedules, and break intervals. Supports overnight intervals that cross midnight. Implementations include time range picker, dual-handle timeline slider, and business hours grid.
Molecules: ml-enter-time-interval, ml-time-interval, ml-time-interval-range, ml-time-interval-selector, ml-time-interval-slider, ml-work-shift-interval

### groupExpandContent (5 molecules)
Allows the user to expand or collapse content sections to see more or less details. Manages multiple sections via Section slot tags with title, disabled, and expanded attributes. Supports accordion mode (single open) or multiple open simultaneously. Implementations include accordion, collapsible, show more/show less, expandable row, and details/summary.
Molecules: ml-accordion, ml-collapsible-panel, ml-readmore-expand, ml-reveal-overlay, ml-single-expand-content

### groupLocatePosition (4 molecules)
Allows the user to inform or visualize a geographic location. Supports address search with autocomplete (suggestions provided by the page via BFF), geolocation capture, and map preview. Value is stored as a JSON string containing lat, lng, and address. Implementations include address autocomplete, map picker, geolocation button, and area selector.
Molecules: ml-address-autocomplete, ml-geolocation-trigger, ml-locate-map-picker, ml-locate-nearby

### groupNavigateSection (5 molecules)
Allows the user to switch between sections within the same context. Sections defined via Tab slot tags with value, title, icon, and disabled attributes. Value is the active tab identifier. Page is responsible for displaying each section content. Implementations include tabs, pills/segmented control, navigation menu, bottom navigation, and pagination.
Molecules: ml-breadcrumb-trail, ml-navigate-pills, ml-navigate-tabs, ml-side-nav-scrollspy, ml-tabs

### groupNavigateSteps (4 molecules)
Allows the user to advance through a sequential multi-step process. Steps defined via Step slot tags with title, description, completed, and disabled attributes. Value is the active step index. Supports linear mode (must complete in order) and free navigation. Implementations include horizontal stepper, vertical stepper, wizard, progress steps.
Molecules: ml-compact-step-indicator, ml-horizontal-stepper, ml-vertical-stepper, ml-wizard-steps

### groupNotifyUser (4 molecules)
Informs the user about events, status changes, or action results. Controlled via visible property. Supports notification types (info, success, warning, error), auto-dismiss with configurable duration, position hints, dismissible toggle, and optional action slot. Implementations include toast, snackbar, banner, alert, and inline alert.
Molecules: ml-alert-modal, ml-contextual-feedback, ml-notify-banner, ml-toast-notification

### groupPlayMedia (4 molecules)
Plays audio or video content. Media sources provided via Source slot tags with fallback format support. Shared contract for both audio and video — swap the component tag to change the player style. Supports autoplay, loop, mute, poster thumbnail, and subtitle tracks. Implementations include video player, audio player, mini player, and media controls.
Molecules: ml-audio-player, ml-image-gallery, ml-pdf-viewer, ml-video-player

### groupRateItem (8 molecules)
Allows the user to rate or score an item. Supports auto-generated options from a numeric range (min/max/step) or custom options via Item slot tags (emoji, icons, text). Value is always a number. Implementations include star rating, thumbs up/down, emoji rating, NPS scale, and satisfaction slider.
Molecules: ml-ces-scale, ml-csat-rating, ml-emoji-mood-scale, ml-numeric-rating-nps, ml-qualitative-feedback-tags, ml-rating-slider, ml-star-rating, ml-thumbs-rating

### groupScanCode (4 molecules)
Captures information via camera (QR code, barcode, document). Component captures image frames and emits them; the page is responsible for decoding via BFF. Supports rear/front camera, auto-capture with configurable interval, and custom result display. Implementations include QR code scanner, barcode reader, document scanner (OCR), and camera viewfinder.
Molecules: ml-scan-code, ml-scan-code-1d, ml-scan-document, ml-scan-ocr

### groupSearchContent (4 molecules)
Allows the user to find content using text search. Emits search events with debounce; page provides suggestions via Suggestion slot tags. Value holds the confirmed result — either a suggestion value or the raw typed text. Supports clear, loading state, and empty state. Implementations include search field, command palette (cmd+k), search with suggestions, and combobox.
Molecules: ml-faceted-search, ml-search-bar, ml-search-filters, ml-search-history

### groupSelectFileForUpload (5 molecules)
Allows the user to select one or more files to be uploaded. Stateless — emits selected File objects via change event; the page is responsible for uploading via BFF. Supports drag-and-drop, file type and size validation, and emits a reject event for invalid files. Implementations include drag-drop zone, file button, multi-file upload, camera capture, and paste from clipboard.
Molecules: ml-file-metadata-uploader, ml-file-upload-dropzone, ml-file-upload-preview, ml-upload-file-list, ml-user-photo-upload

### groupSelectMany (6 molecules)
Allows the user to select one or more options from a list. Value is a comma-separated string of selected item values. Supports searchable filtering, min/max selection limits, grouped items, and disabled options. Implementations include checkbox group, chips/tags, multi-select dropdown, dual list (transfer list), card grid with selection, toggle group, and table (checkbox rows with column headers for comparing attributes).
Molecules: ml-dual-list-select, ml-multi-checkbox-list, ml-multi-select-dropdown, ml-popover-multi-select, ml-table-multi-select, ml-tree-multi-select

### groupSelectOne (12 molecules)
Allows the user to select exactly one option from a list of mutually exclusive choices. Ideal for scenarios where a single, clear decision is required. Layout is chosen via the \`variant\` property: dropdown/combobox (default), radio group, segmented control, list picker, and table (a radio group laid out as a table with column headers — for comparing options that each have multiple attributes, e.g. plan name/price/limits). The selected value is always the chosen item value, regardless of variant.
Molecules: ml-card-selector, ml-combobox, ml-dial-select, ml-discrete-slider, ml-listbox-sidebar-select, ml-radio-group, ml-segmented-control, ml-select, ml-select-dropdown, ml-select-dropdown-img, ml-select-one-autocomplete, ml-table-single-select

### groupShowProgress (5 molecules)
Indicates the progress of an operation or process. Visual primitive designed for composition inside other components. Supports determinate mode (0-100%) and indeterminate mode (unknown duration). Implementations include progress bar, progress ring/circle, spinner, and percentage indicator.
Molecules: ml-circular-progress, ml-indeterminate-spinner, ml-linear-progress, ml-segmented-progress, ml-upload-progress-indicator

### groupTriggerAction (6 molecules)
Allows the user to execute an action or command. Supports Label and Icon slot tags with flexible composition (text only, icon only, or both). Configurable variant (primary, secondary, danger, ghost, link), size, loading state, and icon position. Implementations include button, icon button, FAB, split button, and button group.
Molecules: ml-button-group, ml-button-standard, ml-icon-button, ml-kebab-action-trigger, ml-pagination-control, ml-split-button

### groupViewCard (4 molecules)
Displays an item as an independent visual unit. Composition primitive with flexible slot structure: header (title, description), content, footer, and action areas. All slots are optional. Supports variants (default, outlined, elevated, ghost), clickable, selectable, and loading states. Implementations include standard card, media card, compact card, horizontal card, and interactive card.
Molecules: ml-profile-card, ml-vertical-card, ml-view-card-horizontal, ml-view-card-media

### groupViewChart (6 molecules)
Displays data through graphical representation. Data provided via Series and Point slot tags. All chart implementations share the same data contract — swap the component tag to change visualization. Supports multi-series (Line, Bar, Area, Radar, Scatter) and single-series (Pie, Donut, Funnel). Implementations include bar chart, line chart, area chart, pie chart, donut chart, scatter chart, radar chart, and funnel chart.
Molecules: ml-area-chart, ml-bar-chart, ml-line-chart, ml-pie-chart, ml-radar-chart, ml-scatter-plot

### groupViewData (5 molecules)
Display a collection of data with adaptive layout. The component decides the best presentation based on context (viewport, configuration). Use when displaying multiple records with defined fields and rich content.
Molecules: ml-calendar-view, ml-card-grid, ml-kanban-board, ml-timeline-view, ml-vertical-record-list

### groupViewHierarchy (4 molecules)
Displays hierarchical data structures with parent-child relationships. Uses recursive Node slot tags with free content that can nest indefinitely. Supports expand/collapse of nodes with children, accordion mode (one per level), and expand-all. Implementations include tree view, org chart, cascader, nested list, and mind map.
Molecules: ml-hierarchy-orgchart, ml-hierarchy-tree, ml-hierarchy-tree-diagram, ml-view-hierarchy-mindmap

### groupViewMetric (5 molecules)
Displays a highlighted indicator or metric. Purely visual — all data via slot tags (Label, Value, Icon, Trend with direction attribute, Helper). No value property, no events. Supports loading state. Implementations include big number, KPI card, sparkline, gauge/speedometer, and trend indicator.
Molecules: ml-compact-metric-sparkline, ml-metric-big-number, ml-metric-card, ml-metric-gauge, ml-metric-trend-compare

### groupViewTable (13 molecules)
Displays structured data in tabular format. Data provided via TableHeader, TableBody, TableRow, TableHead, and TableCell slot tags. Supports column sorting, row selection with checkboxes, pagination, and isEditing propagation to web components inside cells. Implementations include data table, simple table, editable grid, virtualized table, and tree table.
Molecules: ml-advanced-data-table, ml-data-table, ml-data-table-minimal, ml-grouping-table, ml-inline-edit-table, ml-lazy-record-detail-table, ml-lcrud-detail-grid, ml-pivot-table, ml-record-form-table, ml-responsive-data-table, ml-responsive-table, ml-side-detail-table, ml-view-table

This project has no local theme.
`;
