/// <mls fileReference="_102040_/l2/molecules/grouplocateposition/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:24.827Z.

export const group = 'groupLocatePosition';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupLocatePosition/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'grouplocateposition--ml-address-autocomplete', defs: '/_102040_/l2/molecules/grouplocateposition/ml-address-autocomplete.defs' },
    { tag: 'grouplocateposition--ml-geolocation-trigger', defs: '/_102040_/l2/molecules/grouplocateposition/ml-geolocation-trigger.defs' },
    { tag: 'grouplocateposition--ml-locate-map-picker', defs: '/_102040_/l2/molecules/grouplocateposition/ml-locate-map-picker.defs' },
    { tag: 'grouplocateposition--ml-locate-nearby', defs: '/_102040_/l2/molecules/grouplocateposition/ml-locate-nearby.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'User types an address and expects search suggestions from your backend.', recommended: ['grouplocateposition--ml-address-autocomplete'] },
    { scenario: 'Only need a single action to capture the current coordinates.', recommended: ['grouplocateposition--ml-geolocation-trigger'] },
    { scenario: 'User should select a precise pin with an embedded map preview.', recommended: ['grouplocateposition--ml-locate-map-picker'] },
    { scenario: 'Choose a nearby area once a base location is known.', recommended: ['grouplocateposition--ml-locate-nearby'] },
];

export const skill = `# groupLocatePosition — available molecules (mls-102040)

Group objective: Allows the user to inform or visualize a geographic location. Supports address search with autocomplete (suggestions provided by the page via BFF), geolocation capture, and map preview. Value is stored as a JSON string containing lat, lng, and address. Implementations include address autocomplete, map picker, geolocation button, and area selector.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| User types an address and expects search suggestions from your backend. | ml-address-autocomplete |
| Only need a single action to capture the current coordinates. | ml-geolocation-trigger |
| User should select a precise pin with an embedded map preview. | ml-locate-map-picker |
| Choose a nearby area once a base location is known. | ml-locate-nearby |

## Molecules (4)

- **grouplocateposition--ml-address-autocomplete** — An address input field that suggests locations as the user types, allowing selection of a geographic position represented by coordinates. It relies on external sources to provide address suggestions and translates user selections into a definitive location value.
- **grouplocateposition--ml-geolocation-trigger** — Capture the device's current geographic position for the groupLocatePosition group. Provide a trigger control that requests a single position reading, presents the result as a coordinate pair, supports suggestion selection, and displays a map preview when configured. Operate in editing and viewing modes while respecting all group contract parameters.
- **grouplocateposition--ml-locate-map-picker** — A location selection interface that combines map visualization with search and geolocation capabilities. It enables users to identify, adjust, and confirm geographic coordinates either by searching for a place, dragging a map marker, or using their current position.
- **grouplocateposition--ml-locate-nearby** — Allow users to find and select nearby locations centered on a specific coordinate. The molecule supports searching for places, selecting from suggestions, viewing the selected location, and optionally using the device's geolocation to set the center point. It can also display a map preview of the selected coordinate.
`;
