/// <mls fileReference="_102040_/l2/molecules/groupexpandcontent/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:22.385Z.

export const group = 'groupExpandContent';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupExpandContent/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupexpandcontent--ml-accordion', layout: { expand: 'accordion' }, defs: '/_102040_/l2/molecules/groupexpandcontent/ml-accordion.defs' },
    { tag: 'groupexpandcontent--ml-collapsible-panel', layout: { expand: 'collapsible' }, defs: '/_102040_/l2/molecules/groupexpandcontent/ml-collapsible-panel.defs' },
    { tag: 'groupexpandcontent--ml-readmore-expand', layout: { expand: 'readmore' }, defs: '/_102040_/l2/molecules/groupexpandcontent/ml-readmore-expand.defs' },
    { tag: 'groupexpandcontent--ml-reveal-overlay', layout: { expand: 'overlay' }, defs: '/_102040_/l2/molecules/groupexpandcontent/ml-reveal-overlay.defs' },
    { tag: 'groupexpandcontent--ml-single-expand-content', layout: { expand: 'collapsible' }, defs: '/_102040_/l2/molecules/groupexpandcontent/ml-single-expand-content.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Only one section should stay open at a time (classic accordion behavior).', recommended: ['groupexpandcontent--ml-accordion'] },
    { scenario: 'Show a teaser with an optional longer explanation.', recommended: ['groupexpandcontent--ml-readmore-expand'] },
    { scenario: 'Highlight a single expandable detail with optional disabled items.', recommended: ['groupexpandcontent--ml-single-expand-content'] },
    { scenario: 'Let users open several configuration panels at once.', recommended: ['groupexpandcontent--ml-collapsible-panel'] },
    { scenario: 'Hide sensitive content behind a deliberate reveal action.', recommended: ['groupexpandcontent--ml-reveal-overlay'] },
];

export const skill = `# groupExpandContent — available molecules (mls-102040)

Group objective: Allows the user to expand or collapse content sections to see more or less details. Manages multiple sections via Section slot tags with title, disabled, and expanded attributes. Supports accordion mode (single open) or multiple open simultaneously. Implementations include accordion, collapsible, show more/show less, expandable row, and details/summary.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Only one section should stay open at a time (classic accordion behavior). | ml-accordion |
| Show a teaser with an optional longer explanation. | ml-readmore-expand |
| Highlight a single expandable detail with optional disabled items. | ml-single-expand-content |
| Let users open several configuration panels at once. | ml-collapsible-panel |
| Hide sensitive content behind a deliberate reveal action. | ml-reveal-overlay |

## Molecules (5)

- **groupexpandcontent--ml-accordion** · expand: accordion — Allow the user to expand and collapse individually labeled content sections arranged vertically. The component can operate in single-expand mode (only one section open at a time) or multi-expand mode (any number of sections open simultaneously), and supports disabled, loading, and per-section disabled states with full keyboard navigation.
- **groupexpandcontent--ml-collapsible-panel** · expand: collapsible — Provide an expandable and collapsible panel interface that allows users to reveal or hide content by interacting with section headers. Supports multiple independent sections, optional subtitles, icons, and controlled expansion behavior.
- **groupexpandcontent--ml-readmore-expand** · expand: readmore — Displays content sections that users can expand to view fully or collapse to hide. Supports both accordion-style single expansion and multiple simultaneous expansions. Provides clear visual states and accessibility for interactive content disclosure.
- **groupexpandcontent--ml-reveal-overlay** · expand: overlay — Conceal sensitive or surprise content behind a visual overlay until the user explicitly chooses to reveal it. Provide a configurable warning before disclosure, allow the user to toggle between hidden and visible states, and inform the system whenever the content is revealed or concealed.
- **groupexpandcontent--ml-single-expand-content** · expand: collapsible — Manage a single expandable section with a clickable header and collapsible body. It must display a title above the section when provided, open and close smoothly, report state changes, and prevent interaction when disabled or loading.
`;
