/// <mls fileReference="_102040_/l2/molecules/groupenterdate/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:45:56.947Z.

export const group = 'groupEnterDate';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupEnterDate/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupenterdate--ml-compact-calendar', layout: { dateInput: 'inline-calendar' }, defs: '/_102040_/l2/molecules/groupenterdate/ml-compact-calendar.defs' },
    { tag: 'groupenterdate--ml-date-picker', layout: { dateInput: 'calendar-popover' }, defs: '/_102040_/l2/molecules/groupenterdate/ml-date-picker.defs' },
    { tag: 'groupenterdate--ml-date-shortcut-picker', layout: { dateInput: 'shortcuts' }, defs: '/_102040_/l2/molecules/groupenterdate/ml-date-shortcut-picker.defs' },
    { tag: 'groupenterdate--ml-inline-calendar', layout: { dateInput: 'inline-calendar' }, defs: '/_102040_/l2/molecules/groupenterdate/ml-inline-calendar.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Space-constrained layouts that still need a month grid.', recommended: ['groupenterdate--ml-compact-calendar'] },
    { scenario: 'Standard form field with a dropdown calendar and placeholder.', recommended: ['groupenterdate--ml-date-picker'] },
    { scenario: 'Fast selection with preset dates like today or next week.', recommended: ['groupenterdate--ml-date-shortcut-picker'] },
    { scenario: 'Always-visible calendar embedded in dashboards or scheduling views.', recommended: ['groupenterdate--ml-inline-calendar'] },
];

export const skill = `# groupEnterDate — available molecules (mls-102040)

Group objective: Allows the user to input a date only (no time). Ideal for birth dates, due dates, contract effective dates, expiration dates, and any scenario where the time of day is irrelevant. Implementations include date picker, masked date input, inline calendar, and month/year picker.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Space-constrained layouts that still need a month grid. | ml-compact-calendar |
| Standard form field with a dropdown calendar and placeholder. | ml-date-picker |
| Fast selection with preset dates like today or next week. | ml-date-shortcut-picker |
| Always-visible calendar embedded in dashboards or scheduling views. | ml-inline-calendar |

## Molecules (4)

- **groupenterdate--ml-compact-calendar** · dateInput: inline-calendar — Allow the user to select a single date from an always-visible inline calendar grid. The calendar renders directly inside the page layout without a popover, shows the current month with navigation controls, highlights today and the selected date, optionally displays week numbers, and respects min/max date bounds. It also has a view-only mode that shows the selected value as plain text.
- **groupenterdate--ml-date-picker** · dateInput: calendar-popover — Allow the user to choose a single date by clicking a trigger button that opens a calendar dropdown. The selected date is displayed on the trigger in a locale-aware format, and a clear action inside the panel resets the selection. The component supports disabled, readonly, required, loading, and error states, and has a view-only mode that shows the value as static text.
- **groupenterdate--ml-date-shortcut-picker** · dateInput: shortcuts — Provide a date selection interface that offers configurable shortcut options for common dates alongside a manual date entry field. It allows users to quickly select predefined dates or enter a date manually, maintaining compliance with the groupEnterDate contract.
- **groupenterdate--ml-inline-calendar** · dateInput: inline-calendar — An inline calendar molecule for selecting a single date, always visible during editing, with monthly navigation. It follows the groupEnterDate contract for data entry and display states.
`;
