/// <mls fileReference="_102040_/l2/molecules/groupselectfileforupload/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:45.526Z.

export const group = 'groupSelectFileForUpload';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupSelectFileForUpload/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupselectfileforupload--ml-file-metadata-uploader', layout: { upload: 'dropzone' }, defs: '/_102040_/l2/molecules/groupselectfileforupload/ml-file-metadata-uploader.defs' },
    { tag: 'groupselectfileforupload--ml-file-upload-dropzone', layout: { upload: 'dropzone' }, defs: '/_102040_/l2/molecules/groupselectfileforupload/ml-file-upload-dropzone.defs' },
    { tag: 'groupselectfileforupload--ml-file-upload-preview', layout: { upload: 'dropzone' }, defs: '/_102040_/l2/molecules/groupselectfileforupload/ml-file-upload-preview.defs' },
    { tag: 'groupselectfileforupload--ml-upload-file-list', layout: { upload: 'button' }, defs: '/_102040_/l2/molecules/groupselectfileforupload/ml-upload-file-list.defs' },
    { tag: 'groupselectfileforupload--ml-user-photo-upload', layout: { upload: 'avatar' }, defs: '/_102040_/l2/molecules/groupselectfileforupload/ml-user-photo-upload.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Need drag-and-drop and bulk validation for many files.', recommended: ['groupselectfileforupload--ml-file-upload-dropzone', 'groupselectfileforupload--ml-upload-file-list'] },
    { scenario: 'Single document upload with an inline preview.', recommended: ['groupselectfileforupload--ml-file-upload-preview'] },
    { scenario: 'Capture a headshot directly from the camera.', recommended: ['groupselectfileforupload--ml-user-photo-upload'] },
    { scenario: 'Collect many spreadsheet files and manage a list.', recommended: ['groupselectfileforupload--ml-upload-file-list'] },
    { scenario: 'Upload CSVs that must include metadata constraints.', recommended: ['groupselectfileforupload--ml-file-metadata-uploader'] },
];

export const skill = `# groupSelectFileForUpload — available molecules (mls-102040)

Group objective: Allows the user to select one or more files to be uploaded. Stateless — emits selected File objects via change event; the page is responsible for uploading via BFF. Supports drag-and-drop, file type and size validation, and emits a reject event for invalid files. Implementations include drag-drop zone, file button, multi-file upload, camera capture, and paste from clipboard.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Need drag-and-drop and bulk validation for many files. | ml-file-upload-dropzone, ml-upload-file-list |
| Single document upload with an inline preview. | ml-file-upload-preview |
| Capture a headshot directly from the camera. | ml-user-photo-upload |
| Collect many spreadsheet files and manage a list. | ml-upload-file-list |
| Upload CSVs that must include metadata constraints. | ml-file-metadata-uploader |

## Molecules (5)

- **groupselectfileforupload--ml-file-metadata-uploader** · upload: dropzone — Enable users to select files via click or drag-and-drop within a designated area, while accommodating supplementary metadata inputs in an integrated customizable region. The molecule manages file validation, maintains the active selection, communicates rejections, and respects disabled and loading states.
- **groupselectfileforupload--ml-file-upload-dropzone** · upload: dropzone — Allow the user to select one or more files for upload by clicking a drop zone area or dragging and dropping files onto it. The component validates selected files against type, size, and count constraints before accepting them, maintains the accumulated list of accepted files, and gives visual feedback for drag, error, loading, and disabled states.
- **groupselectfileforupload--ml-file-upload-preview** · upload: dropzone — Allow the user to select one or more files for upload through a clickable drop zone or drag-and-drop, then display a visual preview grid of the accepted files. Image files are shown as thumbnail previews; non-image files display a "no preview" placeholder. The component validates files against type, size, and count constraints and manages object URLs for image thumbnails.
- **groupselectfileforupload--ml-upload-file-list** · upload: button — Present a list of files intended for upload, enabling users to inspect file details, monitor upload progress, discard unwanted files, and add files through browsing or drag-and-drop, while enforcing validation rules and responding to states that prevent interaction, restrict editing, indicate loading, or signal errors.
- **groupselectfileforupload--ml-user-photo-upload** · upload: avatar — Enable users to select a profile photo through click or drag-and-drop, enforce image-only validation and size/quantity limits, and present a thumbnail preview of the accepted image.
`;
