/// <mls fileReference="_102040_/l2/molecules/groupentertimeinterval/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:19.798Z.

export const group = 'groupEnterTimeInterval';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupEnterTimeInterval/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupentertimeinterval--ml-enter-time-interval', layout: { intervalInput: 'fields' }, defs: '/_102040_/l2/molecules/groupentertimeinterval/ml-enter-time-interval.defs' },
    { tag: 'groupentertimeinterval--ml-time-interval', layout: { intervalInput: 'fields' }, defs: '/_102040_/l2/molecules/groupentertimeinterval/ml-time-interval.defs' },
    { tag: 'groupentertimeinterval--ml-time-interval-range', layout: { intervalInput: 'fields' }, defs: '/_102040_/l2/molecules/groupentertimeinterval/ml-time-interval-range.defs' },
    { tag: 'groupentertimeinterval--ml-time-interval-selector', layout: { intervalInput: 'fields' }, defs: '/_102040_/l2/molecules/groupentertimeinterval/ml-time-interval-selector.defs' },
    { tag: 'groupentertimeinterval--ml-time-interval-slider', layout: { intervalInput: 'slider' }, defs: '/_102040_/l2/molecules/groupentertimeinterval/ml-time-interval-slider.defs' },
    { tag: 'groupentertimeinterval--ml-work-shift-interval', layout: { intervalInput: 'fields' }, defs: '/_102040_/l2/molecules/groupentertimeinterval/ml-work-shift-interval.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Need a quick dropdown-like selector for standard shifts or office hours.', recommended: ['groupentertimeinterval--ml-time-interval-selector', 'groupentertimeinterval--ml-time-interval'] },
    { scenario: 'Users should drag a visual timeline to set availability windows.', recommended: ['groupentertimeinterval--ml-time-interval-slider'] },
    { scenario: 'Configuring shifts that can cross midnight with duration rules.', recommended: ['groupentertimeinterval--ml-work-shift-interval', 'groupentertimeinterval--ml-enter-time-interval'] },
    { scenario: 'Collecting short session ranges with a compact inline layout.', recommended: ['groupentertimeinterval--ml-time-interval-range', 'groupentertimeinterval--ml-time-interval'] },
];

export const skill = `# groupEnterTimeInterval — available molecules (mls-102040)

Group objective: Allows the user to input a time range with a start time and an end time (no date). Ideal for work shifts, business hours configuration, recurring availability windows, class schedules, and break intervals. Supports overnight intervals that cross midnight. Implementations include time range picker, dual-handle timeline slider, and business hours grid.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Need a quick dropdown-like selector for standard shifts or office hours. | ml-time-interval-selector, ml-time-interval |
| Users should drag a visual timeline to set availability windows. | ml-time-interval-slider |
| Configuring shifts that can cross midnight with duration rules. | ml-work-shift-interval, ml-enter-time-interval |
| Collecting short session ranges with a compact inline layout. | ml-time-interval-range, ml-time-interval |

## Molecules (6)

- **groupentertimeinterval--ml-enter-time-interval** · intervalInput: fields — Definir e apresentar um intervalo de horário individual, com hora de início e hora de fim, permitindo alternância entre edição e visualização, aplicando validações e refletindo estados de interação conforme o contrato do grupo.
- **groupentertimeinterval--ml-time-interval** · intervalInput: fields — A molecule that allows a user to view and edit a single time interval within a day, with support for 12-hour and 24-hour formats, optional seconds, overnight intervals, and various validation and visual states. It represents exactly one interval; multiple intervals in the same day are managed by orchestrating multiple instances.
- **groupentertimeinterval--ml-time-interval-range** · intervalInput: fields — Enable users to define a time interval by providing a start time and an end time, ensure the interval is logically valid, display the resulting duration in minutes, and report the interval to the system according to the groupEnterTimeInterval specification.
- **groupentertimeinterval--ml-time-interval-selector** · intervalInput: fields — Allow the user to define a time interval by selecting both a start time and an end time through dropdown pickers with select-based hour, minute, optional second, and optional AM/PM fields. After the start time is confirmed the picker automatically advances to the end time. The component validates interval constraints (min/max duration, overnight spans, same-time rules) and stores both times independently as HH:MM or HH:MM:SS strings.
- **groupentertimeinterval--ml-time-interval-slider** · intervalInput: slider — Allow the user to define a time interval by dragging two overlapping range sliders — one for the start time and one for the end time — over a shared track. The selected segment is highlighted on the track. Both times are displayed as formatted labels above the sliders and validated against min/max time bounds, duration constraints, overnight rules, and same-time rules before being committed.
- **groupentertimeinterval--ml-work-shift-interval** · intervalInput: fields — Enable users to define a single work shift interval with a start time and an end time. The component supports overnight shifts, enforces time constraints, communicates changes to the system, and clearly indicates its current state.
`;
