/// <mls fileReference="_102040_/l2/molecules/groupviewchart/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:47:00.654Z.

export const group = 'groupViewChart';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupViewChart/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupviewchart--ml-area-chart', defs: '/_102040_/l2/molecules/groupviewchart/ml-area-chart.defs' },
    { tag: 'groupviewchart--ml-bar-chart', defs: '/_102040_/l2/molecules/groupviewchart/ml-bar-chart.defs' },
    { tag: 'groupviewchart--ml-line-chart', defs: '/_102040_/l2/molecules/groupviewchart/ml-line-chart.defs' },
    { tag: 'groupviewchart--ml-pie-chart', defs: '/_102040_/l2/molecules/groupviewchart/ml-pie-chart.defs' },
    { tag: 'groupviewchart--ml-radar-chart', defs: '/_102040_/l2/molecules/groupviewchart/ml-radar-chart.defs' },
    { tag: 'groupviewchart--ml-scatter-plot', defs: '/_102040_/l2/molecules/groupviewchart/ml-scatter-plot.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Compare multi-series trends over time with stacked context.', recommended: ['groupviewchart--ml-area-chart'] },
    { scenario: 'Compare category totals for the same time period.', recommended: ['groupviewchart--ml-bar-chart'] },
    { scenario: 'Track precise series movement across intervals.', recommended: ['groupviewchart--ml-line-chart'] },
    { scenario: 'Show share of total for a single series breakdown.', recommended: ['groupviewchart--ml-pie-chart'] },
    { scenario: 'Explore correlation between two metrics across segments.', recommended: ['groupviewchart--ml-scatter-plot'] },
    { scenario: 'Evaluate balanced performance across multiple dimensions.', recommended: ['groupviewchart--ml-radar-chart'] },
];

export const skill = `# groupViewChart — available molecules (mls-102040)

Group objective: Displays data through graphical representation. Data provided via Series and Point slot tags. All chart implementations share the same data contract — swap the component tag to change visualization. Supports multi-series (Line, Bar, Area, Radar, Scatter) and single-series (Pie, Donut, Funnel). Implementations include bar chart, line chart, area chart, pie chart, donut chart, scatter chart, radar chart, and funnel chart.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Compare multi-series trends over time with stacked context. | ml-area-chart |
| Compare category totals for the same time period. | ml-bar-chart |
| Track precise series movement across intervals. | ml-line-chart |
| Show share of total for a single series breakdown. | ml-pie-chart |
| Explore correlation between two metrics across segments. | ml-scatter-plot |
| Evaluate balanced performance across multiple dimensions. | ml-radar-chart |

## Molecules (6)

- **groupviewchart--ml-area-chart** — Present quantitative information as an area chart that highlights volume through filled regions below trend lines. Enable comparison across single or multiple data series, with a default stacked view that shows how individual parts compose a total. Offer interactive discovery, loading feedback, empty state handling, and full accessibility support.
- **groupviewchart--ml-bar-chart** — Display a vertical bar chart that visualizes one or more data series across named categories. The component accepts data through declarative slot elements (Series and Point), renders proportionally sized bars, and lets the user explore individual values through hover tooltips and keyboard-accessible bar buttons.
- **groupviewchart--ml-line-chart** — Display the evolution of numeric data over time using a multi-series line chart. It must visualize connections between ordered data points, allow comparison across series, and handle loading, empty, and dark-mode states.
- **groupviewchart--ml-pie-chart** — Display a pie chart that represents proportional data as colored SVG arc segments. The component accepts data through declarative Series and Point slot elements, renders each slice proportionally to its share of the total, and supports hover tooltips, keyboard interaction, and an accessible data table for screen readers.
- **groupviewchart--ml-radar-chart** — Provide a radar chart for comparing multiple dimensions across one or more data series. It must render labeled axes in a circular layout, display each series as a distinct visual layer, and allow users to explore and select individual values.
- **groupviewchart--ml-scatter-plot** — Display a scatter plot that visualizes data points across X and Y axes, supporting multiple series, interactive tooltips, an optional trend line supplied as a dedicated series, a configurable legend, and accessible data alternatives.
`;
