/// <mls fileReference="_102040_/l2/molecules/groupentertime/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:17.353Z.

export const group = 'groupEnterTime';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupEnterTime/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupentertime--ml-clock-time-picker', layout: { timeInput: 'clock' }, defs: '/_102040_/l2/molecules/groupentertime/ml-clock-time-picker.defs' },
    { tag: 'groupentertime--ml-enter-time-duration', layout: { timeInput: 'duration' }, defs: '/_102040_/l2/molecules/groupentertime/ml-enter-time-duration.defs' },
    { tag: 'groupentertime--ml-time-scroll-picker', layout: { timeInput: 'scroll-picker' }, defs: '/_102040_/l2/molecules/groupentertime/ml-time-scroll-picker.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Users want an analog-style clock for quick selection.', recommended: ['groupentertime--ml-clock-time-picker'] },
    { scenario: 'Kiosk or mobile UI where time columns spin quickly.', recommended: ['groupentertime--ml-time-scroll-picker'] },
    { scenario: 'Capturing elapsed time or shift length with seconds.', recommended: ['groupentertime--ml-enter-time-duration'] },
    { scenario: 'Choosing opening/closing hours in 15-minute steps.', recommended: ['groupentertime--ml-time-scroll-picker'] },
];

export const skill = `# groupEnterTime — available molecules (mls-102040)

Group objective: Allows the user to input a time only (no date). Ideal for business hours, recurring daily schedules, alarm times, opening and closing times, and shift configurations. Implementations include time picker with scrollable columns, masked time input, time spinner, and clock face.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Users want an analog-style clock for quick selection. | ml-clock-time-picker |
| Kiosk or mobile UI where time columns spin quickly. | ml-time-scroll-picker |
| Capturing elapsed time or shift length with seconds. | ml-enter-time-duration |
| Choosing opening/closing hours in 15-minute steps. | ml-time-scroll-picker |

## Molecules (3)

- **groupentertime--ml-clock-time-picker** · timeInput: clock — Allow the user to pick a time of day through a step-by-step clock panel. The user clicks a read-only text input to open a panel, then selects the hour, then the minute, and optionally the second, each on a separate stage. Confirming the selection stores the time in HH:MM or HH:MM:SS format and closes the panel. The component supports 12-hour and 24-hour modes, a configurable minute step, min/max time bounds, and disabled, readonly, error, loading, and view-only states.
- **groupentertime--ml-enter-time-duration** · timeInput: duration — Enable entry and display of time duration in hours and minutes, optionally including seconds, ensuring values conform to valid ranges, boundary limits, and formatting rules. It communicates all changes exclusively through a standardized string-based value contract.
- **groupentertime--ml-time-scroll-picker** · timeInput: scroll-picker — Allow the user to pick a time of day by scrolling through independent columns — one for hours, one for minutes, optionally one for seconds, and optionally one for AM/PM — displayed in a dropdown panel that opens below a read-only text input. Confirming the selection stores the time in HH:MM or HH:MM:SS format. The component supports 12-hour and 24-hour modes, a configurable minute step, min/max time bounds, keyboard Escape to dismiss, and disabled, readonly, error, loading, and view-only states.
`;
