/// <mls fileReference="_102040_/l2/molecules/groupnavigatesection/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:27.261Z.

export const group = 'groupNavigateSection';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupNavigateSection/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupnavigatesection--ml-breadcrumb-trail', layout: { sectionNav: 'breadcrumb' }, defs: '/_102040_/l2/molecules/groupnavigatesection/ml-breadcrumb-trail.defs' },
    { tag: 'groupnavigatesection--ml-navigate-pills', layout: { sectionNav: 'pills' }, defs: '/_102040_/l2/molecules/groupnavigatesection/ml-navigate-pills.defs' },
    { tag: 'groupnavigatesection--ml-navigate-tabs', layout: { sectionNav: 'tabs' }, defs: '/_102040_/l2/molecules/groupnavigatesection/ml-navigate-tabs.defs' },
    { tag: 'groupnavigatesection--ml-side-nav-scrollspy', layout: { sectionNav: 'scrollspy' }, defs: '/_102040_/l2/molecules/groupnavigatesection/ml-side-nav-scrollspy.defs' },
    { tag: 'groupnavigatesection--ml-tabs', layout: { sectionNav: 'tabs' }, defs: '/_102040_/l2/molecules/groupnavigatesection/ml-tabs.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Expose hierarchical sections with a breadcrumb feel at the top of a detail page.', recommended: ['groupnavigatesection--ml-breadcrumb-trail'] },
    { scenario: 'Quickly swap between 3–4 short, peer sections without leaving context.', recommended: ['groupnavigatesection--ml-navigate-pills', 'groupnavigatesection--ml-tabs', 'groupnavigatesection--ml-navigate-tabs'] },
    { scenario: 'Long-form documentation needs section anchors and scroll awareness.', recommended: ['groupnavigatesection--ml-side-nav-scrollspy'] },
    { scenario: 'Provide a classic tabbed interface with clear labels and icons.', recommended: ['groupnavigatesection--ml-tabs', 'groupnavigatesection--ml-navigate-tabs'] },
    { scenario: 'Step-by-step checkout or onboarding where the tabs read like navigation.', recommended: ['groupnavigatesection--ml-navigate-tabs'] },
];

export const skill = `# groupNavigateSection — available molecules (mls-102040)

Group objective: Allows the user to switch between sections within the same context. Sections defined via Tab slot tags with value, title, icon, and disabled attributes. Value is the active tab identifier. Page is responsible for displaying each section content. Implementations include tabs, pills/segmented control, navigation menu, bottom navigation, and pagination.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Expose hierarchical sections with a breadcrumb feel at the top of a detail page. | ml-breadcrumb-trail |
| Quickly swap between 3–4 short, peer sections without leaving context. | ml-navigate-pills, ml-tabs, ml-navigate-tabs |
| Long-form documentation needs section anchors and scroll awareness. | ml-side-nav-scrollspy |
| Provide a classic tabbed interface with clear labels and icons. | ml-tabs, ml-navigate-tabs |
| Step-by-step checkout or onboarding where the tabs read like navigation. | ml-navigate-tabs |

## Molecules (5)

- **groupnavigatesection--ml-breadcrumb-trail** · sectionNav: breadcrumb — Display a hierarchical navigation trail that indicates the user's current position within a nested structure. It enables users to understand the path taken to reach the current level and to navigate back to any previous interactive level.
- **groupnavigatesection--ml-navigate-pills** · sectionNav: pills — A horizontal navigation component that presents selectable sections as pills in a scrollable row. It allows users to choose one section at a time, revealing only the content associated with that section. It supports disabled sections, a loading state, and keyboard navigation.
- **groupnavigatesection--ml-navigate-tabs** · sectionNav: tabs — A tab navigation molecule that allows users to switch between content sections. It supports touch gestures, keyboard navigation, and indicates the active section while keeping inactive sections hidden.
- **groupnavigatesection--ml-side-nav-scrollspy** · sectionNav: scrollspy — Fornecer navegação lateral que vincule a seções da página, destacando automaticamente a seção visível conforme o usuário rola, e permitindo navegação suave até a seção selecionada.
- **groupnavigatesection--ml-tabs** · sectionNav: tabs — Allow the user to switch between multiple named content panels within a section by clicking labelled tab buttons arranged in a horizontal tab bar. The component tracks which tab is active, renders the corresponding panel below the tab bar, and supports icons, disabled tabs, an error message, a loading state, and full keyboard navigation.
`;
