/// <mls fileReference="_102040_/l2/molecules/groupselectone/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:50.681Z.

export const group = 'groupSelectOne';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupSelectOne/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupselectone--ml-card-selector', layout: { selectOne: 'cards' }, defs: '/_102040_/l2/molecules/groupselectone/ml-card-selector.defs' },
    { tag: 'groupselectone--ml-combobox', layout: { selectOne: 'dropdown' }, defs: '/_102040_/l2/molecules/groupselectone/ml-combobox.defs' },
    { tag: 'groupselectone--ml-dial-select', layout: { selectOne: 'dial' }, defs: '/_102040_/l2/molecules/groupselectone/ml-dial-select.defs' },
    { tag: 'groupselectone--ml-discrete-slider', layout: { selectOne: 'slider' }, defs: '/_102040_/l2/molecules/groupselectone/ml-discrete-slider.defs' },
    { tag: 'groupselectone--ml-listbox-sidebar-select', layout: { selectOne: 'listbox' }, defs: '/_102040_/l2/molecules/groupselectone/ml-listbox-sidebar-select.defs' },
    { tag: 'groupselectone--ml-radio-group', layout: { selectOne: 'radio' }, defs: '/_102040_/l2/molecules/groupselectone/ml-radio-group.defs' },
    { tag: 'groupselectone--ml-segmented-control', layout: { selectOne: 'segmented' }, defs: '/_102040_/l2/molecules/groupselectone/ml-segmented-control.defs' },
    { tag: 'groupselectone--ml-select', layout: { selectOne: 'dropdown' }, defs: '/_102040_/l2/molecules/groupselectone/ml-select.defs' },
    { tag: 'groupselectone--ml-select-dropdown', layout: { selectOne: 'dropdown' }, defs: '/_102040_/l2/molecules/groupselectone/ml-select-dropdown.defs' },
    { tag: 'groupselectone--ml-select-dropdown-img', layout: { selectOne: 'dropdown' }, defs: '/_102040_/l2/molecules/groupselectone/ml-select-dropdown-img.defs' },
    { tag: 'groupselectone--ml-select-one-autocomplete', layout: { selectOne: 'dropdown' }, defs: '/_102040_/l2/molecules/groupselectone/ml-select-one-autocomplete.defs' },
    { tag: 'groupselectone--ml-table-single-select', layout: { selectOne: 'table' }, defs: '/_102040_/l2/molecules/groupselectone/ml-table-single-select.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Large visual tiles for plan or package selection.', recommended: ['groupselectone--ml-card-selector'] },
    { scenario: 'Long lists where users need search or autocomplete.', recommended: ['groupselectone--ml-combobox', 'groupselectone--ml-select-one-autocomplete'] },
    { scenario: 'Compact toolbar or mode switch with few options.', recommended: ['groupselectone--ml-segmented-control'] },
    { scenario: 'Stepped scale or rotational control for levels.', recommended: ['groupselectone--ml-dial-select', 'groupselectone--ml-discrete-slider'] },
    { scenario: 'Sidebar navigation with persistent option list.', recommended: ['groupselectone--ml-listbox-sidebar-select'] },
    { scenario: 'Traditional form radio options and short lists.', recommended: ['groupselectone--ml-radio-group', 'groupselectone--ml-select'] },
    { scenario: 'Standard dropdowns with minimal chrome.', recommended: ['groupselectone--ml-select-dropdown', 'groupselectone--ml-select'] },
    { scenario: 'Option lists that need imagery or icons.', recommended: ['groupselectone--ml-select-dropdown-img'] },
    { scenario: 'Comparing multiple attributes before choosing one.', recommended: ['groupselectone--ml-table-single-select'] },
];

export const skill = `# groupSelectOne — available molecules (mls-102040)

Group objective: Allows the user to select exactly one option from a list of mutually exclusive choices. Ideal for scenarios where a single, clear decision is required. Layout is chosen via the \`variant\` property: dropdown/combobox (default), radio group, segmented control, list picker, and table (a radio group laid out as a table with column headers — for comparing options that each have multiple attributes, e.g. plan name/price/limits). The selected value is always the chosen item value, regardless of variant.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Large visual tiles for plan or package selection. | ml-card-selector |
| Long lists where users need search or autocomplete. | ml-combobox, ml-select-one-autocomplete |
| Compact toolbar or mode switch with few options. | ml-segmented-control |
| Stepped scale or rotational control for levels. | ml-dial-select, ml-discrete-slider |
| Sidebar navigation with persistent option list. | ml-listbox-sidebar-select |
| Traditional form radio options and short lists. | ml-radio-group, ml-select |
| Standard dropdowns with minimal chrome. | ml-select-dropdown, ml-select |
| Option lists that need imagery or icons. | ml-select-dropdown-img |
| Comparing multiple attributes before choosing one. | ml-table-single-select |

## Molecules (12)

- **groupselectone--ml-card-selector** · selectOne: cards — A single-selection interface that presents choices as a grid of rich-content cards, enabling the user to review detailed descriptions before choosing one option. It serves high-stakes decisions such as plan selection, template choice, account type, risk profile, or service modality.
- **groupselectone--ml-combobox** · selectOne: dropdown — Allow the user to choose exactly one option from a list by typing into a text field to filter results. A dropdown of matching options appears as the user types or when the field is focused. Optionally, when free-text mode is enabled, any typed value can be accepted even if it does not match a predefined option. The component supports groups, a clearable selection, required and error states, and a read-only view mode.
- **groupselectone--ml-dial-select** · selectOne: dial — Allow the user to choose exactly one option from a circular dial layout. Options are arranged as buttons on concentric rings radiating outward from a central trigger button. Clicking the center opens or closes the rings; clicking a ring item selects it. Items from different groups appear on separate rings, while standalone items share an outermost ring. The component supports an optional search field, keyboard navigation, error and loading states, and a read-only view mode.
- **groupselectone--ml-discrete-slider** · selectOne: slider — A discrete slider that allows selection of exactly one option from a set of mutually exclusive ordinal choices arranged along a horizontal linear scale. It behaves according to the groupSelectOne selection pattern, snapping the selection indicator to fixed stopping points that represent valid options.
- **groupselectone--ml-listbox-sidebar-select** · selectOne: listbox — A permanently open listbox for sidebar master-detail selection that allows choosing a single item from a visible list. It presents options in an always-open panel during editing and collapses to a static label in view mode.
- **groupselectone--ml-radio-group** · selectOne: radio — A single-selection option group that displays all available choices at once without hiding them behind a dropdown. It allows the user to pick exactly one option from a small set, making every option visible for quick comparison and selection.
- **groupselectone--ml-segmented-control** · selectOne: segmented — A single-selection control that presents multiple options as a connected horizontal group of segments. It allows choosing one option from a compact set, showing the selected label when inactive and displaying all options together when active for editing.
- **groupselectone--ml-select** · selectOne: dropdown — Allow the user to choose exactly one option from a conventional click-to-open dropdown list. The component shows a trigger button that displays the current selection or a placeholder, and opens a panel of options when clicked. Unlike the combobox, it accepts no typed input — selection is made entirely by clicking or keyboard navigation. It supports grouped options, required and error states, disabled and readonly modes, and a read-only view mode.
- **groupselectone--ml-select-dropdown** · selectOne: dropdown — Provide a single-selection control that displays the current choice in a collapsed field and reveals a list of available options when activated. It must support searching, validation, and distinct display modes for editing and viewing.
- **groupselectone--ml-select-dropdown-img** · selectOne: dropdown — A selection field that displays the currently chosen option and opens a list of choices when activated. Each option includes an icon alongside text, supporting use cases such as language or country selection where each entry is identified by a representative image or symbol.
- **groupselectone--ml-select-one-autocomplete** · selectOne: dropdown — Allow the user to choose exactly one option from a list by typing into a text field to filter results. A list of matching options appears when the field gains focus. The component supports readonly, disabled, and error states, offers an optional way to clear the selection, and allows full keyboard control.
- **groupselectone--ml-table-single-select** · selectOne: table — Allow users to view and compare multiple detailed options arranged in a table and choose exactly one. The main purpose is to support decisions like selecting the best quote by comparing providers, costs, and timelines side by side.
`;
