/// <mls fileReference="_102040_/l2/molecules/groupviewmetric/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:47:08.295Z.

export const group = 'groupViewMetric';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupViewMetric/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupviewmetric--ml-compact-metric-sparkline', layout: { metric: 'sparkline' }, defs: '/_102040_/l2/molecules/groupviewmetric/ml-compact-metric-sparkline.defs' },
    { tag: 'groupviewmetric--ml-metric-big-number', layout: { metric: 'big-number' }, defs: '/_102040_/l2/molecules/groupviewmetric/ml-metric-big-number.defs' },
    { tag: 'groupviewmetric--ml-metric-card', layout: { metric: 'big-number' }, defs: '/_102040_/l2/molecules/groupviewmetric/ml-metric-card.defs' },
    { tag: 'groupviewmetric--ml-metric-gauge', layout: { metric: 'gauge' }, defs: '/_102040_/l2/molecules/groupviewmetric/ml-metric-gauge.defs' },
    { tag: 'groupviewmetric--ml-metric-trend-compare', layout: { metric: 'big-number' }, defs: '/_102040_/l2/molecules/groupviewmetric/ml-metric-trend-compare.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Single headline KPI that should dominate the dashboard.', recommended: ['groupviewmetric--ml-metric-big-number', 'groupviewmetric--ml-metric-card'] },
    { scenario: 'Metric needs to be read against a target or capacity threshold.', recommended: ['groupviewmetric--ml-metric-gauge'] },
    { scenario: 'Show a short trend line alongside the main value.', recommended: ['groupviewmetric--ml-compact-metric-sparkline'] },
    { scenario: 'Communicate comparison vs a previous period or benchmark.', recommended: ['groupviewmetric--ml-metric-card', 'groupviewmetric--ml-metric-trend-compare'] },
];

export const skill = `# groupViewMetric — available molecules (mls-102040)

Group objective: Displays a highlighted indicator or metric. Purely visual — all data via slot tags (Label, Value, Icon, Trend with direction attribute, Helper). No value property, no events. Supports loading state. Implementations include big number, KPI card, sparkline, gauge/speedometer, and trend indicator.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Single headline KPI that should dominate the dashboard. | ml-metric-big-number, ml-metric-card |
| Metric needs to be read against a target or capacity threshold. | ml-metric-gauge |
| Show a short trend line alongside the main value. | ml-compact-metric-sparkline |
| Communicate comparison vs a previous period or benchmark. | ml-metric-card, ml-metric-trend-compare |

## Molecules (5)

- **groupviewmetric--ml-compact-metric-sparkline** · metric: sparkline — Display a compact metric with an inline sparkline trend, supporting loading states and accessible markup.
- **groupviewmetric--ml-metric-big-number** · metric: big-number — Display a single key metric as a large prominent number accompanied by optional contextual elements: an icon, a descriptive label, a trend indicator with directional coloring, and a helper text. The component is designed for dashboard-style KPI cards where a value needs to be immediately scannable.
- **groupviewmetric--ml-metric-card** · metric: big-number — Present a statistical card that displays a configurable icon, a descriptive label, a primary highlighted value, and a trend indicator with period comparison. It must support a loading state and follow the groupViewMetric contract.
- **groupviewmetric--ml-metric-gauge** · metric: gauge — Display a compact metric card that combines a key value with a horizontal gauge bar, providing an immediate visual sense of progress or fill level. The card optionally includes an icon, a label, a trend badge with directional coloring, and helper text, making it suitable for dashboard KPI widgets that need both a numeric readout and a relative-position indicator.
- **groupviewmetric--ml-metric-trend-compare** · metric: big-number — Display a metric with emphasis on the current value, accompanied by a reference label, previous period context, and a directional trend indicator that communicates performance semantically.
`;
