/// <mls fileReference="_102040_/l2/molecules/groupviewcard/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:58.199Z.

export const group = 'groupViewCard';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupViewCard/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupviewcard--ml-profile-card', layout: { cardLayout: 'profile' }, defs: '/_102040_/l2/molecules/groupviewcard/ml-profile-card.defs' },
    { tag: 'groupviewcard--ml-vertical-card', layout: { cardLayout: 'vertical' }, defs: '/_102040_/l2/molecules/groupviewcard/ml-vertical-card.defs' },
    { tag: 'groupviewcard--ml-view-card-horizontal', layout: { cardLayout: 'horizontal' }, defs: '/_102040_/l2/molecules/groupviewcard/ml-view-card-horizontal.defs' },
    { tag: 'groupviewcard--ml-view-card-media', layout: { cardLayout: 'media' }, defs: '/_102040_/l2/molecules/groupviewcard/ml-view-card-media.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Grid-based product or content tiles with prominent imagery.', recommended: ['groupviewcard--ml-vertical-card', 'groupviewcard--ml-view-card-media'] },
    { scenario: 'Dense list views that need metadata plus a primary action.', recommended: ['groupviewcard--ml-view-card-horizontal'] },
    { scenario: 'Profile or people cards with status, role, and quick actions.', recommended: ['groupviewcard--ml-profile-card'] },
    { scenario: 'Editorial or marketing highlights anchored by a hero visual.', recommended: ['groupviewcard--ml-view-card-media'] },
];

export const skill = `# groupViewCard — available molecules (mls-102040)

Group objective: Displays an item as an independent visual unit. Composition primitive with flexible slot structure: header (title, description), content, footer, and action areas. All slots are optional. Supports variants (default, outlined, elevated, ghost), clickable, selectable, and loading states. Implementations include standard card, media card, compact card, horizontal card, and interactive card.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Grid-based product or content tiles with prominent imagery. | ml-vertical-card, ml-view-card-media |
| Dense list views that need metadata plus a primary action. | ml-view-card-horizontal |
| Profile or people cards with status, role, and quick actions. | ml-profile-card |
| Editorial or marketing highlights anchored by a hero visual. | ml-view-card-media |

## Molecules (4)

- **groupviewcard--ml-profile-card** · cardLayout: profile — A profile and contact card that presents identity, contact details, status, and quick actions for a user or entity. It supports interactive, selected, disabled, loading, and editing states, and allows consumers to compose either vertical or horizontal layouts through its content areas.
- **groupviewcard--ml-vertical-card** · cardLayout: vertical — A vertical card for the groupViewCard group that organizes information into optional sections: header with title and description, body, footer metadata, and actions. It adapts to interactive, loading, disabled, selected, and editing states while staying neutral for use across corporate contexts such as sales pipelines, project boards, recruitment funnels, supplier lists, and executive dashboards.
- **groupviewcard--ml-view-card-horizontal** · cardLayout: horizontal — Provide a compact horizontal card for list items with left media content and right text content, supporting interactive and stateful behaviors.
- **groupviewcard--ml-view-card-media** · cardLayout: media — Display a card with featured media at the top, followed by a structured header, content, footer, and actions. It serves corporate scenarios such as courses, products, properties, job postings, and news through composable content sections.
`;
