/// <mls fileReference="_102040_/l2/molecules/groupenterdatetime/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:01.859Z.

export const group = 'groupEnterDatetime';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupEnterDateTime/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupenterdatetime--ml-datetime-picker', layout: { dateInput: 'calendar-popover' }, defs: '/_102040_/l2/molecules/groupenterdatetime/ml-datetime-picker.defs' },
    { tag: 'groupenterdatetime--ml-enter-datetime-masked-input', layout: { dateInput: 'masked' }, defs: '/_102040_/l2/molecules/groupenterdatetime/ml-enter-datetime-masked-input.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Guided appointment scheduling', recommended: ['groupenterdatetime--ml-datetime-picker'] },
    { scenario: 'Fast keyboard entry of a deadline', recommended: ['groupenterdatetime--ml-enter-datetime-masked-input'] },
    { scenario: 'Accessible date and time selection with locale formatting', recommended: ['groupenterdatetime--ml-datetime-picker', 'groupenterdatetime--ml-enter-datetime-masked-input'] },
    { scenario: 'Entering a datetime in a fixed format', recommended: ['groupenterdatetime--ml-enter-datetime-masked-input'] },
];

export const skill = `# groupEnterDatetime — available molecules (mls-102040)

Group objective: Allows the user to input date and/or time values. Ideal for scheduling, deadlines, date ranges, and appointments. Implementations include date picker, time picker, datetime picker, date range picker, inline calendar, month picker, and year picker.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Guided appointment scheduling | ml-datetime-picker |
| Fast keyboard entry of a deadline | ml-enter-datetime-masked-input |
| Accessible date and time selection with locale formatting | ml-datetime-picker, ml-enter-datetime-masked-input |
| Entering a datetime in a fixed format | ml-enter-datetime-masked-input |

## Molecules (2)

- **groupenterdatetime--ml-datetime-picker** · dateInput: calendar-popover — Allow the user to select a combined date and time through a trigger button that opens a panel containing a monthly calendar grid on the left and scrollable hour and minute selectors on the right. The selection is confirmed explicitly with a Confirm button. The component supports min/max datetime bounds, configurable minute step intervals, timezone-aware display, and disabled, readonly, required, loading, and error states.
- **groupenterdatetime--ml-enter-datetime-masked-input** · dateInput: masked — Allow the user to type a date and time directly into a masked text field. As the user types, the component formats the raw digits into a locale-appropriate date/time pattern (e.g. MM/DD/YYYY HH:MM for en-US, DD/MM/AAAA HH:MM for pt, TT.MM.JJJJ HH:MM for de). When focus leaves the field or Enter is pressed, the typed value is parsed and committed as an ISO datetime string if it is valid; otherwise the field reverts to the last committed value. The component supports min/max datetime bounds, configurable minute step, timezone-aware display, and disabled, readonly, required, loading, and error states.
`;
