/// <mls fileReference="_102040_/l2/molecules/groupnavigatesteps/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:29.896Z.

export const group = 'groupNavigateSteps';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupNavigateSteps/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupnavigatesteps--ml-compact-step-indicator', layout: { steps: 'horizontal' }, defs: '/_102040_/l2/molecules/groupnavigatesteps/ml-compact-step-indicator.defs' },
    { tag: 'groupnavigatesteps--ml-horizontal-stepper', layout: { steps: 'horizontal' }, defs: '/_102040_/l2/molecules/groupnavigatesteps/ml-horizontal-stepper.defs' },
    { tag: 'groupnavigatesteps--ml-vertical-stepper', layout: { steps: 'vertical' }, defs: '/_102040_/l2/molecules/groupnavigatesteps/ml-vertical-stepper.defs' },
    { tag: 'groupnavigatesteps--ml-wizard-steps', layout: { steps: 'horizontal' }, defs: '/_102040_/l2/molecules/groupnavigatesteps/ml-wizard-steps.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Need a classic, single-row progress tracker for checkout or onboarding.', recommended: ['groupnavigatesteps--ml-horizontal-stepper'] },
    { scenario: 'Want rich descriptions per step with more vertical space.', recommended: ['groupnavigatesteps--ml-vertical-stepper'] },
    { scenario: 'Building a guided wizard flow with step-by-step emphasis.', recommended: ['groupnavigatesteps--ml-wizard-steps'] },
    { scenario: 'Space is tight but you still need progress visibility.', recommended: ['groupnavigatesteps--ml-compact-step-indicator'] },
];

export const skill = `# groupNavigateSteps — available molecules (mls-102040)

Group objective: Allows the user to advance through a sequential multi-step process. Steps defined via Step slot tags with title, description, completed, and disabled attributes. Value is the active step index. Supports linear mode (must complete in order) and free navigation. Implementations include horizontal stepper, vertical stepper, wizard, progress steps.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Need a classic, single-row progress tracker for checkout or onboarding. | ml-horizontal-stepper |
| Want rich descriptions per step with more vertical space. | ml-vertical-stepper |
| Building a guided wizard flow with step-by-step emphasis. | ml-wizard-steps |
| Space is tight but you still need progress visibility. | ml-compact-step-indicator |

## Molecules (4)

- **groupnavigatesteps--ml-compact-step-indicator** · steps: horizontal — Provide a compact visual indicator for multi-step workflows that displays progress through numbered steps or completion marks without visible text labels, optimized for narrow spaces such as form headers.
- **groupnavigatesteps--ml-horizontal-stepper** · steps: horizontal — A horizontal stepper that presents a sequence of steps from left to right. Each step shows an icon and a title. Users can navigate between steps by clicking or using keyboard controls. The component visually communicates which steps are completed, active, pending, or unavailable, and can enforce sequential progression or allow free navigation.
- **groupnavigatesteps--ml-vertical-stepper** · steps: vertical — Guide the user through an ordered sequence of steps displayed in a vertical list, indicating which step is currently active, which steps have been completed, and which are still pending. The component supports linear and non-linear navigation modes, per-step disabled and completed states, an optional description per step, and full keyboard navigation.
- **groupnavigatesteps--ml-wizard-steps** · steps: horizontal — A step navigation component that displays a horizontal sequence of workflow steps and manages user progression through them. It indicates active, completed, pending, and disabled states, and enforces either sequential or free-form navigation based on step completion.
`;
