/// <mls fileReference="_102040_/l2/molecules/grouprateitem/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:37.568Z.

export const group = 'groupRateItem';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupRateItem/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'grouprateitem--ml-ces-scale', layout: { rating: 'nps' }, defs: '/_102040_/l2/molecules/grouprateitem/ml-ces-scale.defs' },
    { tag: 'grouprateitem--ml-csat-rating', layout: { rating: 'emoji' }, defs: '/_102040_/l2/molecules/grouprateitem/ml-csat-rating.defs' },
    { tag: 'grouprateitem--ml-emoji-mood-scale', layout: { rating: 'emoji' }, defs: '/_102040_/l2/molecules/grouprateitem/ml-emoji-mood-scale.defs' },
    { tag: 'grouprateitem--ml-numeric-rating-nps', layout: { rating: 'nps' }, defs: '/_102040_/l2/molecules/grouprateitem/ml-numeric-rating-nps.defs' },
    { tag: 'grouprateitem--ml-qualitative-feedback-tags', layout: { rating: 'tags' }, defs: '/_102040_/l2/molecules/grouprateitem/ml-qualitative-feedback-tags.defs' },
    { tag: 'grouprateitem--ml-rating-slider', layout: { rating: 'slider' }, defs: '/_102040_/l2/molecules/grouprateitem/ml-rating-slider.defs' },
    { tag: 'grouprateitem--ml-star-rating', layout: { rating: 'stars' }, defs: '/_102040_/l2/molecules/grouprateitem/ml-star-rating.defs' },
    { tag: 'grouprateitem--ml-thumbs-rating', layout: { rating: 'thumbs' }, defs: '/_102040_/l2/molecules/grouprateitem/ml-thumbs-rating.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Express emotional sentiment with visual cues.', recommended: ['grouprateitem--ml-emoji-mood-scale'] },
    { scenario: 'Measure likelihood to recommend on a 0–10 scale.', recommended: ['grouprateitem--ml-numeric-rating-nps'] },
    { scenario: 'Capture a single descriptive issue or reason.', recommended: ['grouprateitem--ml-qualitative-feedback-tags'] },
    { scenario: 'Allow a continuous score with fine granularity.', recommended: ['grouprateitem--ml-rating-slider'] },
    { scenario: 'Use a familiar star-based rating pattern.', recommended: ['grouprateitem--ml-star-rating'] },
    { scenario: 'Collect a quick yes/no sentiment.', recommended: ['grouprateitem--ml-thumbs-rating'] },
    { scenario: 'Ask for satisfaction using descriptive labels.', recommended: ['grouprateitem--ml-csat-rating'] },
    { scenario: 'Measure effort required to complete a task.', recommended: ['grouprateitem--ml-ces-scale'] },
];

export const skill = `# groupRateItem — available molecules (mls-102040)

Group objective: Allows the user to rate or score an item. Supports auto-generated options from a numeric range (min/max/step) or custom options via Item slot tags (emoji, icons, text). Value is always a number. Implementations include star rating, thumbs up/down, emoji rating, NPS scale, and satisfaction slider.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Express emotional sentiment with visual cues. | ml-emoji-mood-scale |
| Measure likelihood to recommend on a 0–10 scale. | ml-numeric-rating-nps |
| Capture a single descriptive issue or reason. | ml-qualitative-feedback-tags |
| Allow a continuous score with fine granularity. | ml-rating-slider |
| Use a familiar star-based rating pattern. | ml-star-rating |
| Collect a quick yes/no sentiment. | ml-thumbs-rating |
| Ask for satisfaction using descriptive labels. | ml-csat-rating |
| Measure effort required to complete a task. | ml-ces-scale |

## Molecules (8)

- **grouprateitem--ml-ces-scale** · rating: nps — A molecule that presents a 1-to-7 Customer Effort Score rating scale, allowing users to select a numeric value representing their perceived level of effort. It displays options in a horizontal arrangement with a color gradient from low to high effort, supports configurable text labels at the extremes, and adapts its density based on the presence of label and helper content.
- **grouprateitem--ml-csat-rating** · rating: emoji — A customer satisfaction score rating tool that presents five selectable satisfaction levels. Each level displays a distinct icon and a configurable descriptive label. The component highlights the active choice and reveals the associated numeric score.
- **grouprateitem--ml-emoji-mood-scale** · rating: emoji — Provide a visual mood scale using expressive emoji faces to capture user sentiment quickly. It allows selecting a satisfaction level from very unsatisfied to very satisfied using custom-defined options within the groupRateItem contract.
- **grouprateitem--ml-numeric-rating-nps** · rating: nps — A numeric rating selector that presents a scale of numbers for expressing satisfaction levels, commonly used for Net Promoter Score, customer satisfaction, and corporate evaluations. It allows choosing a value from a defined numeric range or from custom-provided options.
- **grouprateitem--ml-qualitative-feedback-tags** · rating: tags — Provide a qualitative feedback selection mechanism that allows users to choose predefined tags to explain their rating. It works alongside a numeric or emoji scale to contextualize the given score. Tags are configurable and support single selection only.
- **grouprateitem--ml-rating-slider** · rating: slider — Provide a precision rating control that lets users express intensity, confidence, or preference along a continuous or discrete scale. It offers finer granularity than star ratings or NPS, supporting both auto-generated numeric ranges and custom-defined options for self-assessment or research contexts.
- **grouprateitem--ml-star-rating** · rating: stars — Provide a numeric rating selection mechanism that allows users to choose a value from 1 to 5. It serves corporate platforms such as training systems, internal product evaluation, supplier portals, and marketplaces. Typical uses include rating courses, suppliers, service interactions, and documents.
- **grouprateitem--ml-thumbs-rating** · rating: thumbs — A binary rating molecule that allows users to choose between two opposing options, typically represented as positive and negative ratings. It follows the groupRateItem contract to provide a compact horizontal choice control that supports editing, viewing, and accessibility needs.
`;
