/// <mls fileReference="_102040_/l2/molecules/groupplaymedia/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:35.049Z.

export const group = 'groupPlayMedia';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupPlayMedia/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupplaymedia--ml-audio-player', defs: '/_102040_/l2/molecules/groupplaymedia/ml-audio-player.defs' },
    { tag: 'groupplaymedia--ml-image-gallery', defs: '/_102040_/l2/molecules/groupplaymedia/ml-image-gallery.defs' },
    { tag: 'groupplaymedia--ml-pdf-viewer', defs: '/_102040_/l2/molecules/groupplaymedia/ml-pdf-viewer.defs' },
    { tag: 'groupplaymedia--ml-video-player', defs: '/_102040_/l2/molecules/groupplaymedia/ml-video-player.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Need a compact audio-only playback bar for podcasts or voice notes.', recommended: ['groupplaymedia--ml-audio-player'] },
    { scenario: 'Need full video playback with poster art and subtitle tracks.', recommended: ['groupplaymedia--ml-video-player'] },
    { scenario: 'Need inline document preview for PDFs inside a workflow.', recommended: ['groupplaymedia--ml-pdf-viewer'] },
    { scenario: 'Need a gallery-style browsing experience for multiple images.', recommended: ['groupplaymedia--ml-image-gallery'] },
    { scenario: 'Need media playback with a shared slot contract across assets.', recommended: ['groupplaymedia--ml-audio-player', 'groupplaymedia--ml-video-player', 'groupplaymedia--ml-pdf-viewer', 'groupplaymedia--ml-image-gallery'] },
];

export const skill = `# groupPlayMedia — available molecules (mls-102040)

Group objective: Plays audio or video content. Media sources provided via Source slot tags with fallback format support. Shared contract for both audio and video — swap the component tag to change the player style. Supports autoplay, loop, mute, poster thumbnail, and subtitle tracks. Implementations include video player, audio player, mini player, and media controls.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Need a compact audio-only playback bar for podcasts or voice notes. | ml-audio-player |
| Need full video playback with poster art and subtitle tracks. | ml-video-player |
| Need inline document preview for PDFs inside a workflow. | ml-pdf-viewer |
| Need a gallery-style browsing experience for multiple images. | ml-image-gallery |
| Need media playback with a shared slot contract across assets. | ml-audio-player, ml-video-player, ml-pdf-viewer, ml-image-gallery |

## Molecules (4)

- **groupplaymedia--ml-audio-player** — Provide an audio player that enables users to play, pause, seek, adjust volume, and mute media. It manages the playback lifecycle, surfaces timing information, and adheres to the groupPlayMedia contract for events, accessibility, error handling, and content sourcing.
- **groupplaymedia--ml-image-gallery** — An image gallery that presents a sequence of images through a main viewing area, a thumbnail strip, and an expanded overlay view. It supports directional navigation, keyboard control, and communicates state changes through the groupPlayMedia contract.
- **groupplaymedia--ml-pdf-viewer** — An embedded document viewer that presents paginated content from a source URL, allowing users to navigate between pages, adjust the viewing scale, and track their position within the document.
- **groupplaymedia--ml-video-player** — Provide a fully accessible video player that renders a native HTML video element from declarative Source and Track slots and exposes custom playback controls for play/pause, seeking, volume, mute, captions, and fullscreen. The component tracks playback state internally and dispatches events on play, pause, end, and time update.
`;
