/// <mls fileReference="_102040_/l2/molecules/groupsearchcontent/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:42.828Z.

export const group = 'groupSearchContent';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupSearchContent/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupsearchcontent--ml-faceted-search', layout: { search: 'bar' }, defs: '/_102040_/l2/molecules/groupsearchcontent/ml-faceted-search.defs' },
    { tag: 'groupsearchcontent--ml-search-bar', layout: { search: 'bar' }, defs: '/_102040_/l2/molecules/groupsearchcontent/ml-search-bar.defs' },
    { tag: 'groupsearchcontent--ml-search-filters', layout: { search: 'bar' }, defs: '/_102040_/l2/molecules/groupsearchcontent/ml-search-filters.defs' },
    { tag: 'groupsearchcontent--ml-search-history', layout: { search: 'bar-with-history' }, defs: '/_102040_/l2/molecules/groupsearchcontent/ml-search-history.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Default search entry point with live suggestions and clear states.', recommended: ['groupsearchcontent--ml-search-bar'] },
    { scenario: 'Highlight recent queries so users can re-run a search quickly.', recommended: ['groupsearchcontent--ml-search-history'] },
    { scenario: 'Provide a rich search experience with facet-driven discovery.', recommended: ['groupsearchcontent--ml-faceted-search'] },
    { scenario: 'Search directly within a filtered list or table of content.', recommended: ['groupsearchcontent--ml-search-filters'] },
];

export const skill = `# groupSearchContent — available molecules (mls-102040)

Group objective: Allows the user to find content using text search. Emits search events with debounce; page provides suggestions via Suggestion slot tags. Value holds the confirmed result — either a suggestion value or the raw typed text. Supports clear, loading state, and empty state. Implementations include search field, command palette (cmd+k), search with suggestions, and combobox.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Default search entry point with live suggestions and clear states. | ml-search-bar |
| Highlight recent queries so users can re-run a search quickly. | ml-search-history |
| Provide a rich search experience with facet-driven discovery. | ml-faceted-search |
| Search directly within a filtered list or table of content. | ml-search-filters |

## Molecules (4)

- **groupsearchcontent--ml-faceted-search** · search: bar — A faceted search component that presents filter options grouped by facets, allows searching within facet options, displays selected filters as breadcrumbs above the search field, and communicates user selections to the containing page through events.
- **groupsearchcontent--ml-search-bar** · search: bar — Provide a search field that accepts text entry, presents inline suggestions, allows clearing the entry, and communicates loading and empty states. It confirms user selections and notifies when text changes, selections are made, or the field is cleared.
- **groupsearchcontent--ml-search-filters** · search: bar — Provide a search interface with a text field, an expandable panel of selectable options, and removable active selection chips. It allows users to search by typing, choose from available options, manage active selections, and communicate all changes to the surrounding system.
- **groupsearchcontent--ml-search-history** · search: bar-with-history — Provide a search input that reveals a dropdown panel of recent and saved searches when focused and empty, and switches to live search suggestions as the user types. Users may select a suggestion or confirm their query to set the field value, with support for loading states, clearing, and disabled states.
`;
