/// <mls fileReference="_102040_/l2/molecules/groupenternumber/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:09.637Z.

export const group = 'groupEnterNumber';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupEnterNumber/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupenternumber--ml-floating-number-input', layout: { labelPlacement: 'floating', numberInput: 'input' }, defs: '/_102040_/l2/molecules/groupenternumber/ml-floating-number-input.defs' },
    { tag: 'groupenternumber--ml-number-input', layout: { labelPlacement: 'top', numberInput: 'input' }, defs: '/_102040_/l2/molecules/groupenternumber/ml-number-input.defs' },
    { tag: 'groupenternumber--ml-number-stepper', layout: { labelPlacement: 'top', numberInput: 'stepper' }, defs: '/_102040_/l2/molecules/groupenternumber/ml-number-stepper.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Simple quantity', recommended: ['groupenternumber--ml-number-input', 'groupenternumber--ml-number-stepper'] },
    { scenario: 'Precise measurement', recommended: ['groupenternumber--ml-number-input', 'groupenternumber--ml-number-stepper', 'groupenternumber--ml-floating-number-input'] },
    { scenario: 'Percentage', recommended: [] },
    { scenario: 'Range selection', recommended: [] },
];

export const skill = `# groupEnterNumber — available molecules (mls-102040)

Group objective: Allows the user to input numeric values. Ideal for quantities, measurements, percentages, ages, weights, and numeric configurations. Implementations include number input, stepper, slider, percentage input, and quantity selector.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Simple quantity | ml-number-input, ml-number-stepper |
| Precise measurement | ml-number-input, ml-number-stepper, ml-floating-number-input |
| Percentage | — |
| Range selection | — |

## Molecules (3)

- **groupenternumber--ml-floating-number-input** · labelPlacement: floating, numberInput: input — Permitir ao usuário inserir ou visualizar números inteiros e decimais em um campo com label flutuante, seguindo regras de acessibilidade, formatação e estados visuais definidos pelo contrato groupEnterNumber.
- **groupenternumber--ml-number-input** · labelPlacement: top, numberInput: input — Allow the user to type a numeric value into a text field that accepts locale-aware decimal input with optional prefix and suffix slot adornments. On blur the component rounds the value to the configured decimal places, clamps it to min/max bounds, and reformats the display text. In view mode it shows the formatted number alongside any prefix or suffix without an editable field.
- **groupenternumber--ml-number-stepper** · labelPlacement: top, numberInput: stepper — Allow the user to enter or adjust a numeric value through a text input flanked by decrement and increment buttons. Each button click changes the value by the configured step, respecting min/max bounds, and the typed input is normalised and clamped on blur. In view mode the component renders the formatted value with optional prefix and suffix adornments but no interactive controls.
`;
