/// <mls fileReference="_102040_/l2/molecules/groupviewdata/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:47:03.060Z.

export const group = 'groupViewData';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupViewData/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupviewdata--ml-calendar-view', layout: { recordsView: 'calendar' }, defs: '/_102040_/l2/molecules/groupviewdata/ml-calendar-view.defs' },
    { tag: 'groupviewdata--ml-card-grid', layout: { recordsView: 'grid' }, defs: '/_102040_/l2/molecules/groupviewdata/ml-card-grid.defs' },
    { tag: 'groupviewdata--ml-kanban-board', layout: { recordsView: 'kanban' }, defs: '/_102040_/l2/molecules/groupviewdata/ml-kanban-board.defs' },
    { tag: 'groupviewdata--ml-timeline-view', layout: { recordsView: 'timeline' }, defs: '/_102040_/l2/molecules/groupviewdata/ml-timeline-view.defs' },
    { tag: 'groupviewdata--ml-vertical-record-list', layout: { recordsView: 'list' }, defs: '/_102040_/l2/molecules/groupviewdata/ml-vertical-record-list.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Summarize multiple records visually with equal emphasis on each item.', recommended: ['groupviewdata--ml-card-grid'] },
    { scenario: 'Highlight milestones or events ordered by time.', recommended: ['groupviewdata--ml-timeline-view', 'groupviewdata--ml-calendar-view'] },
    { scenario: 'Show a scannable list with stacked detail rows.', recommended: ['groupviewdata--ml-vertical-record-list'] },
    { scenario: 'Track work items moving through status columns.', recommended: ['groupviewdata--ml-kanban-board'] },
];

export const skill = `# groupViewData — available molecules (mls-102040)

Group objective: Display a collection of data with adaptive layout. The component decides the best presentation based on context (viewport, configuration). Use when displaying multiple records with defined fields and rich content.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Summarize multiple records visually with equal emphasis on each item. | ml-card-grid |
| Highlight milestones or events ordered by time. | ml-timeline-view, ml-calendar-view |
| Show a scannable list with stacked detail rows. | ml-vertical-record-list |
| Track work items moving through status columns. | ml-kanban-board |

## Molecules (5)

- **groupviewdata--ml-calendar-view** · recordsView: calendar — A calendar visualization that allows users to browse events in monthly or weekly layouts. It organizes time into columns, rows, and cells, enabling users to view event details or initiate new events by selecting time slots.
- **groupviewdata--ml-card-grid** · recordsView: grid — Display records as individual cards arranged in a responsive multi-column grid. Each card combines visual content, title, description, metadata, and actions, offering a spacious, visual alternative to tabular presentation. Suitable for product catalogs, employee directories, project listings, document galleries, and customer panels.
- **groupviewdata--ml-kanban-board** · recordsView: kanban — Display a Kanban board with configurable columns and vertically stacked cards. Enable moving cards between columns, adding new cards per column, and handling loading, empty, and selection states. Notify consumers of card movements and additions.
- **groupviewdata--ml-timeline-view** · recordsView: timeline — Present events in chronological order along a timeline. The molecule must support vertical and horizontal reading flows, group events by date, handle item selection and hover, manage disabled items, and switch between loading, empty, and populated states using designated content regions.
- **groupviewdata--ml-vertical-record-list** · recordsView: list — Display a vertical list of records within the groupViewData context. Each record supports multiple content regions such as visual identifiers, titles, descriptions, metadata, and actions. The molecule manages loading states, empty collections, item selection, and user interaction events.
`;
