/// <mls fileReference="_102040_/l2/molecules/groupviewtable/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:47:10.983Z.

export const group = 'groupViewTable';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupViewTable/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupviewtable--ml-advanced-data-table', defs: '/_102040_/l2/molecules/groupviewtable/ml-advanced-data-table.defs' },
    { tag: 'groupviewtable--ml-data-table', layout: { density: 'comfortable' }, defs: '/_102040_/l2/molecules/groupviewtable/ml-data-table.defs' },
    { tag: 'groupviewtable--ml-data-table-minimal', layout: { density: 'compact' }, defs: '/_102040_/l2/molecules/groupviewtable/ml-data-table-minimal.defs' },
    { tag: 'groupviewtable--ml-grouping-table', defs: '/_102040_/l2/molecules/groupviewtable/ml-grouping-table.defs' },
    { tag: 'groupviewtable--ml-inline-edit-table', defs: '/_102040_/l2/molecules/groupviewtable/ml-inline-edit-table.defs' },
    { tag: 'groupviewtable--ml-lazy-record-detail-table', defs: '/_102040_/l2/molecules/groupviewtable/ml-lazy-record-detail-table.defs' },
    { tag: 'groupviewtable--ml-lcrud-detail-grid', defs: '/_102040_/l2/molecules/groupviewtable/ml-lcrud-detail-grid.defs' },
    { tag: 'groupviewtable--ml-pivot-table', defs: '/_102040_/l2/molecules/groupviewtable/ml-pivot-table.defs' },
    { tag: 'groupviewtable--ml-record-form-table', defs: '/_102040_/l2/molecules/groupviewtable/ml-record-form-table.defs' },
    { tag: 'groupviewtable--ml-responsive-data-table', defs: '/_102040_/l2/molecules/groupviewtable/ml-responsive-data-table.defs' },
    { tag: 'groupviewtable--ml-responsive-table', defs: '/_102040_/l2/molecules/groupviewtable/ml-responsive-table.defs' },
    { tag: 'groupviewtable--ml-side-detail-table', defs: '/_102040_/l2/molecules/groupviewtable/ml-side-detail-table.defs' },
    { tag: 'groupviewtable--ml-view-table', layout: { density: 'compact' }, defs: '/_102040_/l2/molecules/groupviewtable/ml-view-table.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Precisa de ordenação, seleção e recursos completos', recommended: ['groupviewtable--ml-advanced-data-table', 'groupviewtable--ml-data-table', 'groupviewtable--ml-data-table-select'] },
    { scenario: 'Leitura simples e com o mínimo de elementos visuais', recommended: ['groupviewtable--ml-data-table', 'groupviewtable--ml-data-table-minimal', 'groupviewtable--ml-responsive-table', 'groupviewtable--ml-view-table'] },
    { scenario: 'Seleção de várias linhas para ações em lote', recommended: ['groupviewtable--ml-advanced-data-table', 'groupviewtable--ml-data-table-select', 'groupviewtable--ml-lcrud-detail-grid'] },
    { scenario: 'Agrupar registros por uma dimensão', recommended: ['groupviewtable--ml-advanced-data-table', 'groupviewtable--ml-grouping-table', 'groupviewtable--ml-pivot-table'] },
    { scenario: 'Editar valores diretamente na tabela', recommended: ['groupviewtable--ml-inline-edit-table', 'groupviewtable--ml-lcrud-detail-grid'] },
    { scenario: 'Colunas móveis, redimensionáveis e ações de linha', recommended: ['groupviewtable--ml-lcrud-detail-grid'] },
    { scenario: 'Abrir detalhes somente quando necessário', recommended: ['groupviewtable--ml-lazy-record-detail-table', 'groupviewtable--ml-lcrud-detail-grid'] },
    { scenario: 'Análise cruzada de métricas e dimensões', recommended: ['groupviewtable--ml-grouping-table', 'groupviewtable--ml-pivot-table'] },
    { scenario: 'Exibir dados em telas estreitas ou móveis', recommended: ['groupviewtable--ml-responsive-data-table', 'groupviewtable--ml-responsive-table'] },
    { scenario: 'Fluxo completo de criação, edição e exclusão', recommended: ['groupviewtable--ml-inline-edit-table', 'groupviewtable--ml-lcrud-detail-grid'] },
];

export const skill = `# groupViewTable — available molecules (mls-102040)

Group objective: Displays structured data in tabular format. Data provided via TableHeader, TableBody, TableRow, TableHead, and TableCell slot tags. Supports column sorting, row selection with checkboxes, pagination, and isEditing propagation to web components inside cells. Implementations include data table, simple table, editable grid, virtualized table, and tree table.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Precisa de ordenação, seleção e recursos completos | ml-advanced-data-table, ml-data-table, ml-data-table-select |
| Leitura simples e com o mínimo de elementos visuais | ml-data-table, ml-data-table-minimal, ml-responsive-table, ml-view-table |
| Seleção de várias linhas para ações em lote | ml-advanced-data-table, ml-data-table-select, ml-lcrud-detail-grid |
| Agrupar registros por uma dimensão | ml-advanced-data-table, ml-grouping-table, ml-pivot-table |
| Editar valores diretamente na tabela | ml-inline-edit-table, ml-lcrud-detail-grid |
| Colunas móveis, redimensionáveis e ações de linha | ml-lcrud-detail-grid |
| Abrir detalhes somente quando necessário | ml-lazy-record-detail-table, ml-lcrud-detail-grid |
| Análise cruzada de métricas e dimensões | ml-grouping-table, ml-pivot-table |
| Exibir dados em telas estreitas ou móveis | ml-responsive-data-table, ml-responsive-table |
| Fluxo completo de criação, edição e exclusão | ml-inline-edit-table, ml-lcrud-detail-grid |

## Molecules (13)

- **groupviewtable--ml-advanced-data-table** — An interactive data table that supports column sorting, column resizing, column reordering, pagination, an optional per-row total column, and an optional column-sum footer row. The component follows the groupViewTable group contract, using the slot tags TableHeader, TableBody, TableRow, TableHead, TableCell, TableFooter, Empty, and Loading, and respecting all properties and events defined by that contract.
- **groupviewtable--ml-data-table** · density: comfortable — Render a full-featured data table that supports column-based sorting, row selection with checkboxes, pagination, an optional footer, an editing mode, and accessible semantics. The component reads its column definitions and row data from declarative slot elements and exposes rich interaction events so the host application can respond to user actions without the table containing any business logic.
- **groupviewtable--ml-data-table-minimal** · density: compact — Fornecer uma tabela de dados minimalista com ordenação, seleção opcional, estados de vazio e carregamento, paginação e suporte completo a dark mode.
- **groupviewtable--ml-grouping-table** — A table that groups rows according to a user-selected column, displaying collapsible group headers above each set of rows. The grouping column choice is restricted to columns marked as groupable in the predefined header configuration. It follows the groupViewTable group contract, supporting selection, sorting, pagination, editing propagation, loading, empty, error, and disabled states.
- **groupviewtable--ml-inline-edit-table** — Presents tabular records with per-row inline editing and a complete record workflow — edit, save, cancel, delete and create — driven by controls the page supplies. It owns the editing MODE and the placement and visibility of those controls; the page owns the VALUES. It also sorts, paginates, selects rows, and lets a user reorder and resize columns for the session.
- **groupviewtable--ml-lazy-record-detail-table** — Presents records in a sortable, pageable table with on-demand expandable detail rows, following the groupViewTable contract for table content, selection, states, events, and accessibility.
- **groupviewtable--ml-lcrud-detail-grid** — Presents records in a sortable, pageable table whose record detail opens as a scene of its own that replaces the list, for editing or examining one record at a time, following the groupViewTable contract for table content, selection, states, events, and accessibility.
- **groupviewtable--ml-pivot-table** — Provide a pivot table interface that interprets dynamic table intent through column sorting and externally controlled group expansion. It renders tabular data with headers, body, and footer while delegating calculations, groupings, and aggregation logic to the consumer.
- **groupviewtable--ml-record-form-table** — Presents records in a sortable, paginated table with optional selection and record actions, and temporarily replaces that list with a detailed record form for viewing and maintenance, following the groupViewTable contract while the consuming page supplies record content, data updates, and persistence.
- **groupviewtable--ml-responsive-data-table** — Presents data in an accessible, responsive tabular listing using the groupViewTable contract, with optional captions, sorting, row selection, pagination, loading, empty, editing, disabled, and error states.
- **groupviewtable--ml-responsive-table** — Presents structured data through the groupViewTable contract, showing records as a conventional table in wide spaces and as semantically labeled record cards in constrained spaces while retaining the group’s selection, sorting, pagination, data-state, and event behaviors.
- **groupviewtable--ml-side-detail-table** — Presents groupViewTable records as a sortable, paginated table with optional selection and an associated record-detail panel, following the groupViewTable contract for supplied table content, states, selection, editing, sorting, pagination, and events.
- **groupviewtable--ml-view-table** · density: compact — Present data in a clean, minimalist table format that supports ordering, pagination, row selection, and adaptive states for loading and empty data. It must provide clear visual feedback for interactions and maintain full compatibility with dark appearance modes.
`;
