/// <mls fileReference="_102040_/l2/molecules/groupentermoney/index.defs.ts" enhancement="_blank"/>

// Do not change – automatically generated code.
// Generated by agentSyncMoleculeCatalog on 2026-09-02T11:46:07.056Z.

export const group = 'groupEnterMoney';

// The group contract (slots, properties, events, examples) — REFERENCED, never copied:
// the contract is hand-written and no agent may generate it. Read it BEFORE writing markup.
export const usageContract = '/_102020_/l2/aura/molecules/skills/groupEnterMoney/usage';

// Structured list, for deterministic consumers (gates, lints).
// layout = the layoutConfig axes that VARY among this group's siblings.
export const molecules = [
    { tag: 'groupentermoney--ml-currency-input', defs: '/_102040_/l2/molecules/groupentermoney/ml-currency-input.defs' },
    { tag: 'groupentermoney--ml-enter-money-br', defs: '/_102040_/l2/molecules/groupentermoney/ml-enter-money-br.defs' },
];

// The "Quick reference" table (scenario -> recommended). EDITORIAL: written, not derived —
// the one field here that no extraction produces. Edit it HERE; the group page renders it.
export const scenarios = [
    { scenario: 'Locale‑aware editing', recommended: ['groupentermoney--ml-enter-money-br', 'groupentermoney--ml-currency-input'] },
    { scenario: 'Read‑only formatted view', recommended: [] },
    { scenario: 'Bare‑bones UI', recommended: [] },
    { scenario: 'Full feature set (symbol, decimals, loading)', recommended: ['groupentermoney--ml-currency-input'] },
];

export const skill = `# groupEnterMoney — available molecules (mls-102040)

Group objective: Allows the user to input monetary values with locale-aware formatting. Ideal for prices, payments, budgets, and financial transactions. Handles currency symbols, thousand separators, and decimal precision. Implementations include currency input, price field, money input, and currency converter.

## How to choose

1. If the page scenario matches a row below, start from the recommended molecules.
2. Break the tie by the layout axes and by each molecule's full description.
3. Before writing markup, read the group usage contract (usageContract).
   Copy the tag EXACTLY as it appears here.

## Scenarios (quick reference)

| scenario | recommended |
|---|---|
| Locale‑aware editing | ml-enter-money-br, ml-currency-input |
| Read‑only formatted view | — |
| Bare‑bones UI | — |
| Full feature set (symbol, decimals, loading) | ml-currency-input |

## Molecules (2)

- **groupentermoney--ml-currency-input** — Permitir ao usuário inserir e visualizar valores monetários em USD, com formatação e validação conforme padrão en-US, aceitando até 20 dígitos numéricos.
- **groupentermoney--ml-enter-money-br** — A monetary input field that accepts numeric typing and automatically formats values according to Brazilian currency conventions. As the user types digits, the value fills from right to left, applying thousand and decimal separators without displaying the currency symbol.
`;
